diffblue/hw-cbmc

- src/Makefile
- src/config.inc.template
- src/ebmc/Makefile
- src/hw-cbmc/Makefile
- src/ic3/Makefile
- src/smvlang/Makefile
- src/smvlang/parser.y
- src/smvlang/scanner.l
- src/trans-netlist/aig_prop.h
- src/verilog/Makefile
This enables compilation with clang 14, mostly by disabling warnings.
> compile with clang 14

- src/util/ebmc_util.h
The functions have no user (and apparently never had one).
> remove int32_type() and uint64_type()

- src/verilog/Makefile
- src/verilog/verilog_preprocessor.cpp
- src/verilog/verilog_preprocessor.h
- src/verilog/verilog_preprocessor_tokenizer.cpp
- src/verilog/verilog_preprocessor_tokenizer.h
- src/verilog/verilog_preprocessor_tokenizer.l
This adds a flex-based tokenizer to the Verilog preprocessor.  Note that tokenization for Verilog preprocessing differs from tokenization for parsing Verilog.
> New tokenizer for the Verilog preprocessor

- regression/verilog/preprocessor/define1.desc
- regression/verilog/preprocessor/define1.v
- src/verilog/verilog_preprocessor.cpp
- src/verilog/verilog_preprocessor.h
This implements Verilog 2001 preprocessor defines with parameters.
> Verilog preprocessor define arguments

- regression/verilog/preprocessor/include1.desc
- regression/verilog/preprocessor/include1.v
- regression/verilog/preprocessor/include1b.v
- src/verilog/verilog_preprocessor.cpp
- src/verilog/verilog_preprocessor.h
- src/verilog/verilog_preprocessor_tokenizer.cpp
This PR contains two fixes for Verilog include.
> Verilog include fixes

- src/trans-netlist/counterexample_netlist.cpp
- src/trans-netlist/trans_trace.cpp
- src/trans-word-level/counterexample_word_level.cpp
This replaces some direct accesses to fields of ireps and low-level construction of ireps by the appropriate accessors and constructors.
> replace direct access/construction to/of ireps

- src/ebmc/ebmc_base.cpp
- src/ebmc/ebmc_base.h
- src/ebmc/k_induction.cpp
When converting only (solving is disabled), ebmc now converts the properties as well.
> ebmc: convert the properties

- regression/ebmc/ranking-function/counter1.fail.desc
- regression/ebmc/ranking-function/counter1.pass.desc
- regression/ebmc/ranking-function/counter1.sv
- src/ebmc/Makefile
- src/ebmc/ebmc_parse_options.cpp
- src/ebmc/ebmc_parse_options.h
- src/ebmc/ranking_function.cpp
- src/ebmc/ranking_function.h
This adds a facility to prove a given liveness property using a given ranking function.
> ebmc: check a liveness property using a given ranking function

- src/ebmc/Makefile
- src/ebmc/bdd_engine.cpp
- src/ebmc/ebmc_base.cpp
- src/ebmc/ebmc_base.h
- src/ebmc/ebmc_properties.cpp
- src/ebmc/ebmc_properties.h
- src/ebmc/k_induction.cpp
- src/ebmc/ranking_function.cpp
- src/ebmc/show_properties.cpp
- src/ic3/m1ain.cc
- src/ic3/r6ead_input.cc
This introduces a class named `propertiest`, which holds the list of properties for ebmc.
> introduce propertiest

- src/ebmc/Makefile
- src/ebmc/bdd_engine.cpp
- src/ebmc/ebmc_base.cpp
- src/ebmc/ebmc_base.h
- src/ebmc/k_induction.cpp
- src/ebmc/ranking_function.cpp
- src/ebmc/report_results.cpp
- src/ebmc/report_results.h
This extracts the `ebmc_baset::report_results` into a separate function.
> ebmc: extract report_results

- regression/ebmc/neural-liveness/counter1.desc
- regression/ebmc/neural-liveness/counter1.sv
- src/ebmc/Makefile
- src/ebmc/ebmc_parse_options.cpp
- src/ebmc/ebmc_parse_options.h
- src/ebmc/neural_liveness.cpp
- src/ebmc/neural_liveness.h
This adds an implementation of neural liveness checking, i.e., a
guess-verify loop that uses a given neural engine to guess candidate ranking
functions for a liveness property.
> ebmc: neural liveness

- src/verilog/parser.y
Following the SystemVerilog grammar, `local_parameter_declaration` and `parameter_declaration` are derived from `package_or_generate_item_declaration`, and not `module_or_generate_item`.
> Verilog: grammar for parameter_declaration

- src/verilog/parser.y
This sorts the rules in the grammar according to their section number in IEEE Std 1800-2017.
> Verilog: sort the grammar according to the standard

- src/ebmc/random_traces.cpp
The random trace generator uses incremental SAT to apply a sequence of input constraints to the given model.
The inputs hence need to be frozen to accommodate SAT preprocessing and incremental solving.
> random trace generator now freezes the inputs

- src/verilog/parser.y
This renames and reorders the production rules to match the System Verilog standard 1800-2017.
> Verilog: grammar for generate regions

- src/verilog/verilog_expr.h
- src/verilog/verilog_generate.cpp
- src/verilog/verilog_language.cpp
- src/verilog/verilog_module.cpp
- src/verilog/verilog_module.h
- src/verilog/verilog_typecheck.h
This adds modules that are instantiated in generate regions as dependencies.
> Verilog: modules instantiated in generate regions are dependencies

- regression/verilog/modules/parameters7.desc
- regression/verilog/modules/parameters7.sv
This adds a test for typing parameters.
> Verilog: add KNOWNBUG test for typed parameters

- src/trans-word-level/instantiate_word_level.cpp
`wl_instantiatet::instantiate_rec` now returns a value instead of modifying its argument in place.
> ebmc: wl_instantiatet::instantiate_rec now returns a value

- regression/ebmc/ranking-function/lexicographic_ranking_function1.desc
- regression/ebmc/ranking-function/lexicographic_ranking_function1.sv
This adds a test for liveness checking using a lexicographic ranking function.
> ebmc: test for lexicographic ranking functions

- regression/ebmc/liveness-to-safety/failing1.desc
- regression/ebmc/liveness-to-safety/failing1.sv
- regression/ebmc/liveness-to-safety/failing2.desc
- regression/ebmc/liveness-to-safety/failing2.sv
- regression/ebmc/liveness-to-safety/passing1.desc
- regression/ebmc/liveness-to-safety/passing1.sv
- regression/ebmc/liveness-to-safety/passing2.desc
- regression/ebmc/liveness-to-safety/passing2.sv
- src/ebmc/Makefile
- src/ebmc/ebmc_base.cpp
- src/ebmc/ebmc_base.h
- src/ebmc/ebmc_error.h
- src/ebmc/ebmc_parse_options.cpp
- src/ebmc/ebmc_parse_options.h
- src/ebmc/ebmc_properties.h
- src/ebmc/liveness_to_safety.cpp
- src/ebmc/liveness_to_safety.h
- src/trans-word-level/next_symbol.h
- src/trans-word-level/property.h
This adds the liveness to safety translation to EBMC.
> ebmc: liveness to safety translation

- src/ebmc/bdd_engine.cpp
This changes the interface between the BDD engine and ebmc by switching from `ebmc_baset` to directly calling the relevant APIs.
> ebmc: simplify BDD/ebmc interface

- regression/ebmc/p-command-line-option/p-command-line-option1.desc
This is a fixup for be75859e0948921dd4461e71058371f4fe12cdda, updating the expected output to match the new status results.
> update test with new status result

- regression/verilog/casts/static_cast1.desc
- regression/verilog/casts/static_cast1.sv
- src/verilog/parser.y
- src/verilog/scanner.l
- src/verilog/verilog_typecheck_expr.cpp
This adds support for System Verilog typecast expressions.
> Verilog: System Verilog typecasts

- src/ebmc/Makefile
- src/ebmc/bmc.cpp
- src/ebmc/bmc.h
- src/ebmc/ebmc_base.cpp
- src/ebmc/ebmc_base.h
- src/ebmc/k_induction.cpp
This extracts the functionality to do plain BMC into a separate file.
> ebmc: factor out BMC

- src/verilog/parser.y
This moves statement-related rules into the right section, and adjusts initial/always rules to match the System Verilog standard.
> Verilog: move grammar rules into correct section

- regression/verilog/class/class1.desc
- regression/verilog/class/class1.sv
- src/verilog/parser.y
This adds the grammatical rules for System Verilog classes.
> Verilog: System Verilog classes

- regression/verilog/package/package1.desc
- regression/verilog/package/package1.sv
- src/verilog/parser.y
- src/verilog/verilog_parser.h
This adds the grammatical rules for System Verilog packages.
> Verilog: System Verilog packages

- regression/verilog/functioncall/functioncall6.desc
- regression/verilog/functioncall/functioncall6.v
- src/verilog/parser.y
This adjusts the grammar for function definitions and functions calls to match 1800-2017.
> Verilog: grammar for function definitions and function calls

- src/verilog/verilog_synthesis.cpp
This replaces usage of `throw 0` with `errort()`.
> Verilog: use errort in verilog_synthesis

- .github/workflows/pull-request-checks.yaml
This upgrades the cache action to v4, and also sets `save-always: true`.
> CI: cache action now v4

- regression/verilog/functioncall/functioncall_as_constant1.desc
- regression/verilog/functioncall/functioncall_as_constant1.v
- src/verilog/verilog_elaborate.cpp
- src/verilog/verilog_interfaces.cpp
- src/verilog/verilog_typecheck.h
This moves the creation of function and tasks symbols (and any symbols therein) to the elaboration phase.
> Verilog: elaborate functions and tasks

- .github/workflows/pull-request-checks.yaml
- regression/verilog/Makefile
- regression/verilog/assignment-to-concatenation/test.desc
- regression/verilog/assignment-to-range1/test.desc
- regression/verilog/bit-extract/bit-extract1.desc
- regression/verilog/bit-extract/bit-extract2.desc
- regression/verilog/case/case3.desc
- regression/verilog/case/case4.desc
- regression/verilog/functioncall/functioncall3.desc
- regression/verilog/generate/generate-for2.desc
- regression/verilog/generate/generate-reg1.desc
- regression/verilog/generate1/test.desc
- regression/verilog/indexed-part-select1/test.desc
- regression/verilog/modules/ports2.desc
- regression/verilog/multiple_assign1/test.desc
- regression/verilog/nondet1/test.desc
- regression/verilog/replication1/test.desc
- regression/verilog/system_verilog_assertion/system_verilog_assertion3.desc
This exercises additonal functionality of the solver backend, and is hence worth running in CI.
> CI: run the Verilog tests with Z3

- regression/verilog/SVA/eventually1.desc
- regression/verilog/SVA/eventually1.sv
- regression/verilog/SVA/eventually2.desc
- regression/verilog/SVA/eventually2.sv
- src/trans-word-level/instantiate_word_level.cpp
- src/verilog/expr2verilog.cpp
- src/verilog/expr2verilog_class.h
- src/verilog/sva_expr.h
- src/verilog/verilog_typecheck_expr.cpp
This adds support for the weak variant of the SVA eventually operator to the front-end and the BMC backend.
> Verilog: support for weak eventually

- regression/ebmc/smv/bmc_unsupported_property1.desc
- regression/ebmc/smv/bmc_unsupported_property1.smv
- regression/ebmc/smv/bmc_unsupported_property2.desc
- regression/ebmc/smv/bmc_unsupported_property2.smv
- regression/ebmc/smv/smv_ltlspec4.desc
- regression/ebmc/smv/smv_ltlspec4.smv
- src/temporal-logic/normalize_property.cpp
- src/temporal-logic/normalize_property.h
- src/trans-word-level/property.cpp
This adds support for properties of the type `F φ` and `AF φ` to the BMC engine.
> BMC for F φ

- regression/verilog/modules/variable_module_port1.desc
- regression/verilog/modules/variable_module_port1.sv
- src/verilog/parser.y
SystemVerilog allows module ports to have a variable kind.
> SystemVerilog: module ports may have variable kind

- examples/Benchmarks/experiments.sh
This should help reproduce experiments, should anyone desire to do so.
> Jasper and VC Formal evaluation script

- regression/ebmc/smv-netlist/smv_netlist1.desc
- regression/ebmc/smv-netlist/smv_netlist1.v
- src/trans-netlist/netlist.cpp
SMV identifiers may start with `$`, `_`, `a`-`z`, `A`-`Z`, `0`-`9`.  In addition, `#`, `-`, and `.`  are allowed as subsequent characters.
> SMV netlists: SMV identifier syntax

- src/trans-netlist/trans_trace.h
- src/trans-netlist/trans_trace_netlist.cpp
- src/trans-word-level/trans_trace_word_level.cpp
> `trans_tracet::assignmentt` now has full constructor

- regression/verilog/SVA/sequence4.desc
- regression/verilog/SVA/sequence4.sv
This adds a KNOWNBUG test for the SVA sequence concatenation operator.
> KNOWNBUG test for SVA sequence concatenation

- .github/workflows/ebmc-release.yaml
> CI: `actions/create-release@v1` needs token

- .github/workflows/pull-request-checks.yaml
- regression/ebmc/example1/test.desc
- regression/ebmc/example3/test.desc
- regression/ebmc/example4_reset/test.desc
- regression/ebmc/example4_trace/test.desc
- regression/ebmc/example5/test.desc
- regression/ebmc/netlist/netlist-trace1.desc
- regression/ebmc/ring_buffer_bdd/test.desc
- regression/ebmc/ring_buffer_induction/test.desc
- regression/verilog/Array1/test.desc
- regression/verilog/delays/delay_with_unit1.desc
- regression/verilog/delays/time_literals1.desc
- regression/verilog/preprocessor/include2.desc
- src/Makefile
- src/ebmc/Makefile
- src/ebmc/ebmc_parse_options.cpp
- src/verilog/verilog_expr.h
- src/verilog/verilog_preprocessor.cpp
- src/verilog/verilog_preprocessor.h
This adds a Windows 2022 Visual Studio CI job.
> Add Windows/Visual Studio CI job

- regression/ebmc/range_type/range_type6.desc
This includes an implementation for arithmetic on range types.
> bump CBMC dependency

- regression/verilog/SVA/sequence_implication1.desc
- regression/verilog/SVA/sequence_implication1.sv
> Verilog: KNOWNBUG test for sequence implication

- src/ebmc/bdd_engine.cpp
- src/ebmc/bdd_engine.h
- src/ebmc/ebmc_parse_options.cpp
- src/ebmc/property_checker.cpp
This moves the invocation of the BDD engine into the `property_checker(...)` function.
> Move BDD engine invocation

- src/ebmc/bdd_engine.cpp
- src/ebmc/bdd_engine.h
- src/ebmc/ebmc_parse_options.cpp
- src/ebmc/k_induction.cpp
- src/ebmc/k_induction.h
- src/ebmc/property_checker.cpp
This moves the invocation of the k-induction engine into the `property_checker(...)` function.
> Move k-induction invocation

- regression/verilog/synthesis/posedge_vector.desc
> posedge_vector test should be CORE

- regression/verilog/SVA/sequence3.desc
- regression/verilog/SVA/sequence3.sv
- src/temporal-logic/normalize_property.cpp
- src/temporal-logic/normalize_property.h
This fixes the normalization of `##[*]` φ.
> SVA: fix normalization of ##[*] φ

- regression/verilog/elaboration/type_operator.desc
The missing feature was added with #357.
> test elaboration/type_operator already works

- src/ebmc/bdd_engine.cpp
- src/ebmc/cegar/bmc_cegar.cpp
- src/ebmc/property_checker.cpp
- src/trans-netlist/bmc_map.cpp
- src/trans-netlist/bmc_map.h
- src/trans-netlist/unwind_netlist.cpp
- src/trans-netlist/unwind_netlist.h
The `bmc_mapt` class now has a constructor that completely constructs the object.
> add `bmc_mapt` constructor

- regression/verilog/SVA/issue669.desc
- regression/verilog/SVA/issue669.sv
This adds the example given in issue #669 as a KNOWNBUG.
> add example from #669 as KNOWNBUG

- regression/ebmc/smv/smv_if1.desc
- regression/ebmc/smv/smv_if1.smv
- src/smvlang/expr2smv.cpp
- src/smvlang/parser.y
- src/smvlang/scanner.l
- src/smvlang/smv_typecheck.cpp
This adds NuSMV's `?:`, which C-style semantics.
> SMV: add `?:`

- regression/verilog/expressions/power1.desc
- src/verilog/aval_bval_encoding.cpp
- src/verilog/aval_bval_encoding.h
- src/verilog/verilog_synthesis.cpp
- src/verilog/verilog_typecheck_base.cpp
- src/verilog/verilog_typecheck_base.h
- src/verilog/verilog_typecheck_expr.cpp
- src/verilog/verilog_typecheck_expr.h
This adds the lowering for four-valued power expressions.
> Verilog: four-valued power

- src/trans-word-level/property.cpp
This delivers on the promise of #737 and really removes the unused `namespacet` parameter from the word-level BMC property encoder.
> word-level BMC: remove ns parameter

- regression/verilog/SVA/followed-by2.desc
- regression/verilog/SVA/followed-by2.sv
This adds tests for the SVA followed-by operators.
> SVA: add tests for `#-#` and `#=#`

- regression/verilog/expressions/this1.desc
- regression/verilog/expressions/this1.sv
- src/verilog/parser.y
- src/verilog/verilog_typecheck_expr.cpp
This adds support for the System Verilog `this` keyword.
> Verilog: this

- src/temporal-logic/nnf.cpp
- src/temporal-logic/nnf.h
- src/temporal-logic/normalize_property.cpp
This extracts the NNF functionality in `normalize_property_rec` into a separate function.
> extract NNF from `normalize_property_rec`

- src/vlindex/verilog_indexer.cpp
- src/vlindex/verilog_indexer.h
- src/vlindex/vlindex_parse_options.cpp
- src/vlindex/vlindex_parse_options.h
This adds indexing for SystemVerilog named properties and named sequences.
> vlindex: properties and sequences

- src/vlindex/verilog_indexer.cpp
- src/vlindex/verilog_indexer.h
This adds parsing and counting for SystemVerilog checkers.
> vlindex: support checkers

- regression/ebmc/netlist/netlist-conversion2.desc
- regression/ebmc/netlist/netlist-conversion2.sv
- src/trans-netlist/trans_to_netlist.cpp
This implements the conversion of Verilog primitive gates into netlists.
> netlist conversion for Verilog primitive gates

- src/ebmc/Makefile
- src/ebmc/bdd_engine.cpp
- src/ebmc/ebmc_base.cpp
- src/ebmc/netlist.cpp
- src/ebmc/netlist.h
- src/ebmc/property_checker.cpp
This extracts the step for creating a netlist from a transition system into a function in a separate file.
> extract netlist creation

- regression/ebmc/range_type/range_type7.desc
- regression/ebmc/range_type/range_type7.smv
- regression/ebmc/range_type/range_type8.desc
- regression/ebmc/range_type/range_type8.smv
This adds two further tests for SMV range types.
> SMV: two tests for range types

- regression/smv/boolean/boolean_expected1.desc
- regression/smv/boolean/boolean_expected1.smv
- regression/smv/boolean/boolean_expected2.desc
- regression/smv/boolean/boolean_expected2.smv
- regression/smv/boolean/boolean_expected3.desc
- regression/smv/boolean/boolean_expected3.smv
- regression/smv/boolean/boolean_expected4.desc
- regression/smv/boolean/boolean_expected4.smv
This adds four tests for cases when a Boolean is expected.
> SMV: add tests for type checking errors

- regression/smv/define/define1.desc
- regression/smv/define/define1.smv
- src/smvlang/parser.y
This removes an ill-fated attempt to do typing while parsing SMV.
> SMV: removing typing from parser

- regression/ebmc/k-induction/k-induction6.desc
- regression/ebmc/k-induction/k-induction6.sv
> KNOWNBUG test for engine heuristic

- regression/verilog/functioncall/named_block1.desc
- regression/verilog/functioncall/named_block1.sv
> Verilog: KNOWNBUG for declarations inside a named block inside a function

- src/verilog/expr2verilog.cpp
- src/verilog/verilog_expr.h
- src/verilog/verilog_simplifier.cpp
This adds classes for the existing reduction operator expressions.
> Verilog: classes for the reduction operator expressions

- src/smvlang/Makefile
- src/smvlang/smv_range.cpp
- src/smvlang/smv_range.h
- src/smvlang/smv_typecheck.cpp
Minor cleanup on `smv_ranget`.
> SMV: cleanup `smv_ranget`

- regression/smv/boolean/boolean_expected1.desc
- regression/smv/boolean/boolean_expected2.desc
- regression/smv/boolean/boolean_expected3.desc
- regression/smv/boolean/boolean_expected4.desc
- regression/smv/boolean/boolean_expected5.desc
- regression/smv/boolean/boolean_expected5.smv
- src/smvlang/smv_typecheck.cpp
Error reporting is improved when a Boolean is expected.
> SMV: error reporting for Boolean expressions

- regression/smv/LTL/smv_ltlspec4.desc
- regression/smv/LTL/smv_ltlspec4.smv
- regression/smv/range-type/range_type1.desc
- regression/smv/range-type/range_type1.smv
- src/smvlang/parser.y
- src/smvlang/smv_parse_tree.h
- src/smvlang/smv_typecheck.cpp
NuSMV allows naming properties.
> SMV: named properties

- CHANGELOG
- regression/smv/expressions/xnor1.desc
- regression/smv/expressions/xnor1.smv
- src/smvlang/expr2smv.cpp
- src/smvlang/parser.y
- src/smvlang/smv_typecheck.cpp
NuSMV adds the `xnor` operator to the SMV languaage.
> SMV: xnor operator

- regression/smv/boolean/boolean_expected5.desc
- regression/smv/range-type/range_type5.desc
- regression/smv/range-type/range_type8.desc
- src/smvlang/smv_typecheck.cpp
This splits up the process of determining the type of a given expression and the process of converting a typed expression to a given other type.
> SMV: separate type checking and type conversion

- regression/verilog/SVA/sequence_repetition5.desc
- regression/verilog/SVA/sequence_repetition5.sv
- src/verilog/expr2verilog.cpp
- src/verilog/expr2verilog_class.h
- src/verilog/parser.y
- src/verilog/sva_expr.cpp
- src/verilog/sva_expr.h
- src/verilog/verilog_typecheck_sva.cpp
This implements SVA's consecutive sequence repetition with a given bounded range for the number of repetitions.
> SVA: consecutive repetition with range

- CHANGELOG
- regression/verilog/SVA/sequence_first_match1.desc
- regression/verilog/SVA/sequence_first_match2.desc
- regression/verilog/SVA/sequence_first_match2.sv
- src/trans-word-level/property.cpp
- src/trans-word-level/sequence.cpp
- src/verilog/expr2verilog.cpp
- src/verilog/expr2verilog_class.h
- src/verilog/parser.y
- src/verilog/sva_expr.h
- src/verilog/verilog_typecheck_sva.cpp
This implements the SVA `first_match` operator.
> SVA: `first_match`

- regression/verilog/SVA/sequence_and2.desc
- regression/verilog/SVA/sequence_and2.sv
- regression/verilog/SVA/sequence_and3.desc
- regression/verilog/SVA/sequence_and3.sv
This adds two tests for SVA's sequence `and` operator.
> SVA: two tests for sequence `and`

- regression/smv/smv/bdd_unsupported_property.desc
- regression/smv/smv/bdd_unsupported_property.smv
- src/ebmc/bdd_engine.cpp
- src/temporal-logic/temporal_logic.cpp
- src/temporal-logic/temporal_logic.h
This adds conversion from a fragment of LTL to CTL, for the benefit of the BDD engine.
> LTL to CTL conversion

- regression/verilog/synthesis/rf1.desc
- regression/verilog/synthesis/rf1.sv
> KNOWNBUG test for assignment to packed array with non-zero starting index

- regression/ebmc-spot/sva-buechi/followed-by1.bdd.desc
- regression/ebmc-spot/sva-buechi/followed-by1.bmc.desc
- regression/ebmc-spot/sva-buechi/followed-by2.bdd.desc
- regression/ebmc-spot/sva-buechi/followed-by2.bmc.desc
- regression/ebmc-spot/sva-buechi/followed-by3.desc
- regression/ebmc-spot/sva-buechi/followed-by4.bdd.desc
- regression/ebmc-spot/sva-buechi/followed-by4.bmc.desc
- src/temporal-logic/ltl_sva_to_string.cpp
This adds the two followed-by SVA operators to the SVA-to-Buechi translation.
> SVA-to-Buechi: `#-#` and `#=#`

- regression/verilog/SVA/cycle_delay_star2.desc
- regression/verilog/SVA/cycle_delay_star2.sv
This adds a test for the `SVA ##[*]` sequence operator.
> KNOWNBUG test for `##[*]`

- .github/workflows/pull-request-checks.yaml
- regression/ebmc-spot/sva-buechi/cycle_delay_star2.bdd.desc
- regression/ebmc-spot/sva-buechi/cycle_delay_star2.bmc.desc
- regression/ebmc-spot/sva-buechi/cycle_delay_star3.bdd.desc
- regression/ebmc-spot/sva-buechi/cycle_delay_star3.bmc.desc
- regression/verilog/SVA/cycle_delay_star3.bdd.desc
- regression/verilog/SVA/cycle_delay_star3.bmc.desc
- regression/verilog/SVA/cycle_delay_star3.sv
This adds a test for SVA's `##[*]` operator, for BDDs, BMC, Buechi->BMC and Buechi->BDD.
> Test for SVA `##[*] ...`

- regression/verilog/structs/array_in_struct1.desc
> Test structs/array_in_struct1.desc works
