diffblue/hw-cbmc

src/Makefile

The vhdl module uses the file converter from ansi-c, and hence has a dependency on cprover.dir.

vhdl module depends on cprover.dir

---

src/smvlang/Makefile
src/verilog/Makefile
src/vhdl/Makefile

1) This tells bison the desired name of the generated header file, as opposed to trying to rename it.
2) The names of CLEANFILES and dependencies are fixed.
Fixes issue #37.

fix for bison invocations for frontends

---

src/util/ebmc_util.h
src/verilog/parser.y
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_type.cpp

This removes the copies of `integer_typet` and `natural_typet` introduced in f374bd54197a19d117f1258e32c4242109449831, and replaces them by including the appropriate header file.

remove copies of integer_typet and natural_typet

---

src/verilog/verilog_typecheck_expr.cpp

This replaces two uses of `exprt::make_bool` by `make_boolean_expr`.

replace exprt::make_bool by make_boolean_expr

---

src/verilog/verilog_expr.h

This strenthens the type hierarchy for `function_call_exprt`, which is now derived from `binary_exprt`.

function_call_exprt is a binary_exprt

---

src/verilog/verilog_expr.h

This strenthens the type hierarchy for `hierarchical_identifier_exprt`, which are now derived from `binary_exprt`.

hierarchical_identifier_exprt is a binary_exprt

---

src/vcegar/discover_predicates.cpp
src/vcegar/simulator.cpp
src/verilog/parser.y
src/verilog/verilog_expr.h
src/verilog/verilog_generate.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck_expr.cpp

This replaces usage of the deprecated `exprt::copy_to_operands` by `add_to_operands`.

replace exprt::copy_to_operands by add_to_operands

---

src/smvlang/parser.y
src/smvlang/smv_typecheck.cpp
src/verilog/parser.y
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck_expr.cpp
src/vhdl/parser.y

This replaces usage of the deprecated `exprt::move_to_operands` by `add_to_operands(std::move(...))`.

replace exprt::move_to_operands by add_to_operands(std::move(...))

---

src/verilog/verilog_synthesis.cpp

This avoids constructing an `equal_exprt` that is temporarily type-inconsistent.  Instead, the operands are type-casted before calling the constructor of `equal_exprt`.

avoid constructing type-inconsistent equality

---

src/ebmc/output_verilog.cpp
src/hw-cbmc/gen_interface.cpp
src/hw-cbmc/map_vars.cpp
src/smvlang/expr2smv.cpp
src/trans-netlist/trans_trace.cpp
src/verilog/expr2verilog.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_base.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_type.cpp
src/vhdl/expr2vhdl.cpp

This avoids direct use of `typet::subtypet()` by casting to the appropriate derived type, which is usually `array_typet`.

avoid typet::subtype()

---

src/ebmc/negate_property.cpp

This adds std::move to avoid copy when returning expressions in ebmc.

add std::move to avoid copy when returning expressions

---

src/verilog/verilog_typecheck.cpp

This replaces one instance of `forall_named_irep` by a standard ranged for.

replace forall_named_irep by ranged for

---

src/ebmc/bdd_engine.cpp
src/ebmc/k_induction.cpp
src/ebmc/negate_property.cpp
src/ebmc/output_verilog.cpp
src/hw-cbmc/next_timeframe.cpp
src/ic3/r1ead_input.cc
src/smvlang/expr2smv.cpp
src/smvlang/parser.y
src/smvlang/smv_typecheck.cpp
src/trans-netlist/instantiate_netlist.cpp
src/trans-netlist/trans_to_netlist.cpp
src/trans-netlist/trans_trace.cpp
src/trans-netlist/unwind_netlist.cpp
src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/property.cpp
src/trans-word-level/word_level_trans.cpp
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/parser.y
src/verilog/verilog_generate.cpp
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h
src/vhdl/vhdl_typecheck.cpp

Objects with specific expression class types are casted up to that type. This avoids direct, unguarded accesses to `exprt::op0`, `op1`, etc.

strengthen expression class typing

---

src/ic3/p0ick_lit.cc

To enable compilation with clang++, this silences a warning that `count_eq` is not read.

silence a warning that count_eq is not read

---

regression/verilog/include/not_found1.v
regression/verilog/include/test.desc
src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h

This outputs the source location of the include directive when the file that is to be included is not found.

Verilog: output source location when an include file is not found

---

.github/workflows/pull-request-checks.yaml

This changes the name of the branch we do CI on to the new default branch.

change the name of the branch we do CI on to 'main'

---

src/Makefile

This fixes the `clean` target in the Makefile, and extends it to clean the CBMC dependency.

fix 'make clean'

---

README.md

The compilation instructions in README.md have ommitted the necessity to download minisat prior to starting the build.

fix compilation instructions in README.md

---

regression/verilog/preprocessor/unknown_directive.desc
regression/verilog/preprocessor/unknown_directive.v
src/verilog/verilog_preprocessor.cpp

To aid debugging, the Verilog fontend now includes the source location of any unknown preprocessor directive.

Verilog: print source location on unknown preprocessor directive

---

regression/verilog/preprocessor/unknown_directive.desc
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_base.h
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h

This adds a command line option --preprocess to obtain the output of the preprocessor when applied to the given file.

ebmc: add command-line option --preprocess

---

src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h

This adds a complete constructor for `verilog_preprocessort::filet`.

Verilog preprocessor: add proper constructor for filet

---

src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h

Replace and remove a local variant of util's `concat_dir_file` in the Verilog preprocessor.

Verilog: use concat_dir_file instead of local variant

---

src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor_error.h

This adds a class for exceptions in the Verilog preprocessor, as opposed to throwing the integer 0.

Verilog: add a class for exceptions in the preprocessor

---

regression/verilog/preprocessor/ifdef1.desc
regression/verilog/preprocessor/ifdef1.v
regression/verilog/preprocessor/ifdef2.desc
regression/verilog/preprocessor/ifdef2.v
regression/verilog/preprocessor/multi-line-define1.desc
regression/verilog/preprocessor/multi-line-define2.desc
regression/verilog/preprocessor/multi-line-define2.v
regression/verilog/preprocessor/multi-line-define3.desc
regression/verilog/preprocessor/multi-line-define3.v
src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h

This keeps the line-count in the Verilog parser in sync by emitting newlines when multi-line `define` directives are read.

Verilog preprocessor: line count sync

---

regression/verilog/generate/generate-for1.desc
regression/verilog/generate/generate-for1.v
src/verilog/parser.y

This adjusts the Verilog grammar to allow a generate-for module item without `begin` ...  `end`.

Verilog: SystemVerilog 2012 generate for without begin ... end

---

regression/verilog/modules/module_not_found1.desc
regression/verilog/modules/module_not_found1.v

This adds a test for the common scenario that a module that is instantiated is not found.

Verilog: add test for module not found

---

src/verilog/verilog_generate.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This changes `convert_const_expression` to return a value, instead of using a reference parameter.
This also removes one instance of `to_integer_non_constant`.

Verilog: convert_const_expression now returns a value

---

src/verilog/verilog_expr.h
src/verilog/verilog_generate.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h

This adds `verilog_module_exprt` to improve typing in the Verilog frontend.

introduce verilog_module_exprt

---

src/verilog/verilog_expr.h
src/verilog/verilog_parameterize_module.cpp

To strengthen the typing in the Verilog frontend, this introduces a class `verilog_parameter_declt`.

introduce verilog_parameter_declt

---

regression/ebmc/example4_trace/test.desc
regression/ebmc/netlist/netlist-trace1.desc
regression/ebmc/netlist/netlist-trace1.sv
src/trans-netlist/trans_trace.cpp
src/trans-netlist/trans_trace_netlist.cpp

After switching to a hexadecimal bitvector representation, we need to convert the value in the counterexample trace to get a binary output.

ebmc: bugfix for binary values in trace

---

src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_base.cpp
src/hw-cbmc/hw_cbmc_parse_options.cpp
src/trans-netlist/trans_trace_netlist.cpp
src/trans-netlist/trans_trace_netlist.h
src/trans-word-level/trans_trace_word_level.cpp
src/trans-word-level/trans_trace_word_level.h

We now have rvalues, and can hence return a larger data structure without the cost of copying.

ebmc: return trans_tracet

---

src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_base.h
src/ebmc/ebmc_solvers.cpp
src/ebmc/k_induction.cpp

This renames the `do_bmc` and `finish_bmc` methods to make it obvious which one is bit level and which one is word level.

ebmc: rename do_bmc and related methods

---

src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h

This removes the command line option and the help entry.  The code for it was removed in 2018 with f7db43518eace6a3404c8007f9c4516b02964088.

ebmc: remove --smt1

---

src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_base.h
src/trans-word-level/property.cpp
src/trans-word-level/property.h
src/trans-word-level/trans_trace_word_level.cpp
src/trans-word-level/trans_trace_word_level.h

To enable the use of decision procedures that do not expose a CNF-style API, switch the use of literalt to handle expressions.

ebmc: use handles

---

src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_base.h
src/hw-cbmc/map_vars.cpp
src/hw-cbmc/map_vars.h
src/trans-netlist/bmc_map.cpp
src/trans-netlist/bmc_map.h
src/trans-netlist/trans_trace.cpp
src/trans-netlist/trans_trace.h
src/trans-word-level/counterexample_word_level.h
src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/instantiate_word_level.h
src/trans-word-level/property.cpp
src/trans-word-level/property.h
src/trans-word-level/trans_trace_word_level.cpp
src/trans-word-level/trans_trace_word_level.h
src/trans-word-level/unwind.cpp
src/trans-word-level/unwind.h

There are numerous vectors that have the same size as the number of timeframes, and hence, the natural type for the number of timeframes or timeframe indices is `std::size_t`.

ebmc: timeframe indices are now size_t

---

README.md

The copy of minisat in src/ic3 includes zlib.h, which may not already be present.

README.md: we need zlib.h

---

src/trans-word-level/unwind.cpp

This changes the status output when unwinding transition systems to use the term 'in-state constraints' to refer to state invariant constraints, as opposed to 'general constraints'.

ebmc: 'general constraints' -> 'in-state constraints'

---

regression/ebmc/random-traces/boolean1.desc
regression/ebmc/random-traces/boolean1.v
regression/ebmc/random-traces/bv1.desc
regression/ebmc/random-traces/bv1.v
src/ebmc/Makefile
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_base.h
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/random_traces.cpp
src/ebmc/random_traces.h
src/hw-cbmc/map_vars.cpp
src/hw-cbmc/map_vars.h
src/trans-netlist/bmc_map.cpp
src/trans-netlist/bmc_map.h
src/trans-netlist/trans_trace.cpp
src/trans-netlist/trans_trace.h
src/trans-word-level/counterexample_word_level.h
src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/instantiate_word_level.h
src/trans-word-level/property.cpp
src/trans-word-level/property.h
src/trans-word-level/trans_trace_word_level.cpp
src/trans-word-level/trans_trace_word_level.h
src/trans-word-level/unwind.cpp
src/trans-word-level/unwind.h

This adds a facility to generate a given number of random traces, using the solver, with a given length, and using a given random seed.
By default, traces are written to the console, but may alternatively be stored in VCD format, one file per trace.
Depends on #108.

ebmc: generate random traces

---

src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_base.h
src/ebmc/ebmc_parse_options.cpp
src/ebmc/k_induction.cpp
src/ebmc/random_traces.cpp
src/ebmc/show_trans.cpp
src/ic3/m1ain.cc

The term 'transition system' is more specific than 'model'.

ebmc: rename get_model to get_transition_system

---

src/ebmc/Makefile
src/ebmc/ebmc_base.h
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/ebmc_solvers.cpp
src/ebmc/show_formula_solver.cpp
src/ebmc/show_formula_solver.h

This prints the formula generated by BMC in a syntax designed for readability.

ebmc: add --show-formula

---

src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_base.h
src/ebmc/ebmc_solvers.cpp
src/ebmc/k_induction.cpp
src/ebmc/random_traces.cpp
src/ebmc/ranking_function.cpp
src/ebmc/show_trans.cpp

This groups the symbol table, the main symbol pointer and the transition system expression into one type.

ebmc: create transition_systemt class and member

---

src/Makefile
src/aiger/Makefile
src/common
src/config.inc
src/ebmc/Makefile
src/hw-cbmc/Makefile
src/ic3/Makefile
src/satqe/Makefile
src/smvlang/Makefile
src/trans-netlist/Makefile
src/trans-word-level/Makefile
src/vcegar/Makefile
src/verilog/Makefile
src/vhdl/Makefile

This reduces replication between Makefiles in the repo by moving shared lines into a new file 'common'.
This also enables partial builds by locally calling 'make' in any directory.

introduce a repo-local common file

---

src/ebmc/ebmc_base.h
src/ebmc/transition_system.h

This introduces a separate header file for `ebmc_baset::transition_systemt`.

ebmc: move transition_systemt into a header file

---

src/ebmc/ebmc_error.h
src/ebmc/ebmc_parse_options.cpp
src/ebmc/random_traces.cpp
src/ebmc/ranking_function.cpp

This introduces an exception class, `ebmc_errort`, for signalling errors in ebmc, instead of using integer return values.

ebmc: use exceptions for error reporting

---

src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_base.h
src/ebmc/ebmc_parse_options.cpp
src/ebmc/k_induction.cpp
src/ebmc/ranking_function.cpp

A 'transition system' does not include properties, hence we split out the code that discovers the properties into a new function.

ebmc: split out property parsing from get_transition_system

---

src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/trans-netlist/trans_trace.cpp
src/trans-netlist/trans_trace.h

This adds a new command line option `--json-result`, which outputs the analysis results, including traces, if any, into a file as JSON.

ebmc: add --json-result command line option

---

src/ebmc/ebmc_base.cpp
src/trans-netlist/trans_trace.cpp
src/trans-netlist/trans_trace.h

We can avoid a copy with rvalues, and hence, can effectively return the XML data structure instead of using a reference parameter.

translation of trans_tracet to XML now returns a value

---

src/ebmc/diatest.h
src/ebmc/ebmc_parse_options.cpp

This re-enables the long lost --diatest command line option.

ebmc: re-enable --diatest

---

regression/ebmc/random-traces/boolean1.desc
regression/ebmc/random-traces/bv1.desc
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/random_traces.cpp

The term 'bound' is uncommon in random simulation.  Use the common term 'trace steps' instead of bound.  Note that this counts transition steps, not transition system states.  A trace with one step has two states.

random traces: use --trace-steps instead of --bound

---

src/ebmc/ebmc_base.cpp
src/ebmc/random_traces.cpp
src/hw-cbmc/hw_cbmc_parse_options.cpp
src/trans-netlist/trans_trace.cpp
src/trans-netlist/trans_trace.h

This splits up `show_trans_trace` by format, i.e., console output, XML and JSON, and hence, the existing VCD output is no longer asymmetric.

ebmc: split up show_trans_trace by format

---

regression/ebmc/random-traces/boolean1.desc
regression/ebmc/random-traces/bv1.desc
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/random_traces.cpp

The `--random-traces` option can now be given an additional option `--number-of-traces` to specify how many traces to generate.

ebmc: --random-traces now uses --number-of-traces

---

src/verilog/expr2verilog.cpp
src/vhdl/expr2vhdl.cpp

This replaces a conversion from bitvector constants to mp_integer that assumes a binary representation to `numeric_cast_v`, which hides the details of the representation.

bugfix: bitvectors are no longer binary

---

src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_parse_options.cpp

This sets the message handler verbosity when not using `ebmc_baset`.

ebmc: set verbosity when not using ebmc_baset

---

src/ebmc/random_traces.cpp
src/ebmc/random_traces.h

This exposes the function `random_traces` to use random trace generation as a component.

ebmc: expose API for random tracing

---

src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h
src/ebmc/ranking_function.cpp
src/ebmc/ranking_function.h

This exposes two functions, `parse_ranking_function` and `is_ranking_function`, to enable the use of ranking function checking as a component.

ebmc: add API for ranking function checking

---

src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h

`ebmc_propertiest::from_transition_system` now returns the properties extracted from the transition system by value.

ebmc: properties are now returned by value

---

src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h

This moves the code in `ebmc_baset::parse_property`, which parses a property expression string,
into `ebmc_propertiest`, to enable re-use by other modules.

ebmc: move parse_property into ebmc_propertiest

---

src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_error.h
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_solver_factory.h
src/ebmc/k_induction.cpp
src/ebmc/neural_liveness.cpp
src/ebmc/random_traces.cpp
src/ebmc/ranking_function.cpp
src/ebmc/show_trans.cpp
src/ebmc/transition_system.cpp
src/ebmc/transition_system.h
src/ic3/m1ain.cc

`get_transition_system` now returns the transition system by value, as opposed to via a reference.

ebmc: get_transition_system now returns by value

---

regression/ebmc/Next-in-Property1/test.desc
regression/ebmc/neural-liveness/counter1.desc
regression/ebmc/ranking-function/counter1.fail.desc
regression/ebmc/ranking-function/counter1.pass.desc
src/verilog/expr2verilog.cpp

This adds parentheses when outputting SVA operators that have SVA operators as operands.

expr2verilog: precedence for SVA operators

---

src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_typecheck.cpp

`verilog_declt::declarations()` returns a vector that always contains declarations.  This commit changes the return type of the method to reflect this.

Verilog: strenthen typing of verilog_declt::declarations()

---

regression/verilog/modules/nonansi1.v
src/verilog/parser.y

This adds support for `parameter_port_list` in the module header.

Verilog: Modules with nonansi headers

---

regression/verilog/comments/eof-in-comment1.desc
regression/verilog/comments/eof-in-comment1.v
src/verilog/verilog_preprocessor_tokenizer.l

This changes the tokenizer of the Verilog preprocessor to allow single line comments to end on EOF.

Verilog: allow EOF in single line comments

---

regression/verilog/modules/parameter_ports1.v
src/verilog/parser.y

This extends the set of variants of supported parameter port declarations.

Verilog: parameter port declarations

---

src/verilog/Makefile
src/verilog/verilog_expr.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_generate.cpp
src/verilog/verilog_interpreter.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This renames three methods in the Verilog frontend to use the term `constant_expression` instead of `const_expression`, to match the term used in the Verilog standard.

Verilog: cleanup constant expression typechecking

---

regression/verilog/functioncall/functioncall3.desc
regression/verilog/functioncall/functioncall3.v
src/verilog/parser.y
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck_type.cpp

Closer in style to the SystemVerilog grammar, the parser now returns integer declarations using a type integer, as opposed to a port class integer.

Verilog: parser returns integer as type, not port class

---

src/verilog/verilog_expr.h
src/verilog/verilog_parameterize_module.cpp
src/verilog/verilog_typecheck.h

This strengthens the typing when dealing with parameter declarators.

Verilog: introduce verilog_parameter_declt::declaratort

---

.github/workflows/pull-request-checks.yaml

This adds a job for building and testing ebmc on CentOS 8, which is the
currently 'active' EDA operating system.

CI: add CentOS 8 job

---

regression/verilog/modules/missing_connection1.desc
regression/verilog/modules/missing_connection1.v
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp

This fixes the error message that is emitted when the number of module instance arguments does not match the number of ports of the instantiated module.

Verilog: fix error message when arguments do not match port numbers

---

regression/verilog/modules/localparam2.desc
regression/verilog/modules/localparam2.v
src/verilog/verilog_typecheck_expr.cpp

Parameters have default values, which are not overridden.  These must be constant folded.

Verilog: elaborate parameter values that have not been overridden

---

regression/verilog/modules/module_instance_identifier1.desc
regression/verilog/modules/module_instance_identifier1.v
src/verilog/verilog_parameterize_module.cpp

This partially reverts f374bd54197a19d117f1258e32c4242109449831, which has replaced `integer2string` by `.to_long`, and which has caused characters instead of digits to be appended to a module identifier.

Verilog: append integer as decimal, not binary

---

src/ebmc/output_verilog.cpp

The Verilog RTL output happens after elaboration, and any generate constructs have been expanded.

Verilog: ignore genvar variables when outputting RTL

---

regression/verilog/generate/generate-reg1.desc
regression/verilog/generate/generate-reg1.v

Registers in generate blocks get named after the block identifier.  This adds a test for this scenario.

Verilog: add a KNOWNBUG for registers in generate blocks

---

regression/verilog/generate/generate-for2.desc
regression/verilog/generate/generate-for2.v
src/verilog/parser.y

This fixes generate blocks without label, which the parser has simply dropped.

Verilog: fix generate begin ... end

---

regression/verilog/modules/parameters5.desc
regression/verilog/modules/parameters5.v

This adds a failing test for accessing module parameters from the outside of a module via the instance identifier.

Verilog: add KNOWNBUG test for access to parameters of an instance

---

regression/verilog/modules/ports3.desc
regression/verilog/modules/ports3.v

This adds a failing test that exposes a bug where the type of a register depends on the type of a module input.

Verilog: add KNOWNBUG test for ANSI-style module headers

---

src/verilog/verilog_interfaces.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This consolidates the code that forms the identifier for a symbol from a `base_name` in the context of a module, function/task within that module, and the named block within the module or function/task.

introduce verilog_typecheck_exprt::hierarchical_identifier(base_name)

---

src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp

This introduces a class for generate block module items, to strengthen typing in the Verilog frontend.

introduce verilog_generate_blockt

---

src/verilog/verilog_expr.h
src/verilog/verilog_parameterize_module.cpp
src/verilog/verilog_typecheck.h

This documents an existing irep-based data structure used internally in the Verilog frontend.

introduce verilog_module_sourcet

---

regression/verilog/modules/parameters6.desc
regression/verilog/modules/parameters6.v

Verilog parameters may depend on parameters declared later in the module.

Verilog: add a KNOWNBUG test for a parameter dependency

---

src/verilog/verilog_expr.h

Replace `extern line` (a GNU extension) by `inline`.

extern inline -> inline

---

src/verilog/verilog_expr.h

This will enable stronger typing in the Verilog frontend.

Verilog: introduce verilog_local_parameter_declt

---

src/verilog/verilog_expr.h
src/verilog/verilog_generate.cpp
src/verilog/verilog_typecheck.h

This extracts a method to process declarations during the elaboration of generate constructs.

Verilog: introduce elaborate_generate_decl

---

regression/verilog/generate/generate-reg2.desc
regression/verilog/generate/generate-reg2.v
src/verilog/verilog_generate.cpp

This fixes the Verilog front-end to add symbols for variables that are declared in generate constructs.

Verilog: add symbols for variables in generate constructs

---

src/verilog/parser.y

This adds a case from the Verilog grammar that allows variables as delay values.  Constructs like that will now be parsed, but not synthesized.

Verilog: delay values can be identifiers

---

src/verilog/parser.y

This moves data-type related rules into the order given in IEEE 1800-2017.

Verilog: sort some rules according to standard

---

regression/verilog/data-types/typedef1.desc
regression/verilog/data-types/typedef1.sv
src/verilog/parser.y
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_parse_tree.h

Following IEEE 1800 2017, this allows typedefs as `block_item` or `package_or_generate_item`.

Verilog: typedefs inside modules

---

src/verilog/verilog_interfaces.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h

This strengthens the typing in the Verilog front-end.

Verilog: use verilog_module_sourcet when checking the ports

---

src/trans-netlist/trans_trace.cpp

VCD trace output no longer relies on the internal representation of numbers as binary.

fix values in VCD traces

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h

Return the result of expression synthesis instead of modifying in place.

Verilog: synth_expr now returns the result

---

src/verilog/Makefile
src/verilog/verilog_elaborate_constants.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h

System Verilog introduces enum constants, which are elaborated like parameters.  Hence rename the method that elaborates them to the more general `elaborate_constants`.

Verilog: rename elaborate_parameters to elaborate_constants

---

src/verilog/parser.y

This sorts the rules in section A.2.10 Assertion declarations into the order given in System Verilog 1800-2017.

Verilog: sort rules for section A.2.10 Assertion declarations

---

src/verilog/parser.y

This re-sorts and renames the rules in section A.4.2 Generated instantiation to match those in the System Verilog standard 1800-2017.

Verilog: grammar rules in section A.4.2 generated instantiation

---

src/verilog/parser.y

This cleans out grammar rules that have been superseded by more permissive System Verilog rules.

Verilog: clean out unused rules

---

src/verilog/parser.y
src/verilog/scanner.l
src/verilog/verilog_typecheck_expr.cpp

This adds missing keywords and operators given in System Verilog 1800-2017.

Verilog: add missing operators and keywords

---

src/verilog/scanner.l

The two operators -> and <-> are valid System Verilog, but not Verilog.
Introduce SYSTEM_VERILOG_OPERATOR macro.

System Verilog operators

---

regression/verilog/system_verilog_assertion/system_verilog_assertion4.sv
src/verilog/parser.y

The SystemVerilog grammar allows parentheses around property expressions. This changes the Verilog grammar accordingly.

Verilog: allow parentheses in property expressions

---

src/ebmc/ebmc_solver_factory.cpp

This enables the use of console colors when `--show-formula` is used without `--outfile`.

ebmc: use console colors for --show-formula

---

regression/ebmc/ranking-function/counter_with_reset1.fail.desc
regression/ebmc/ranking-function/counter_with_reset1.pass.desc
regression/ebmc/ranking-function/counter_with_reset1.sv
src/ebmc/ranking_function.cpp

The ranking function facility now allows selecting a specific property using the `--property` command-line option.

ebmc: --ranking-function now honors --property

---

regression/ebmc/traces/waveform1.desc
regression/ebmc/traces/waveform1.smv
src/ebmc/Makefile
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/report_results.cpp
src/ebmc/waveform.cpp
src/ebmc/waveform.h

This adds a "horizontal" output format for traces, where the timeframe is on the x axis and the identifier of the state variable are on the y axis.

ebmc: add waveform output

---

.github/workflows/pull-request-checks.yaml
README.md
src/ic3/minisat/CMakeLists.txt
src/ic3/minisat/minisat/core/Main.cc
src/ic3/minisat/minisat/simp/Main.cc
src/ic3/minisat/minisat/utils/ParseUtils.h

the existing dependency on `zlib` seems to be unnecessary.
`zlib.h` is only included in the `ic3` Minisat and applying similar patches to what is used in CBMC removes this dependency.
In the long run, `ic3` Minisat should maybe be replaced with CBMC Minisat

Remove dependency zlib

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck_expr.cpp

This uses the slightly shorter `display_name` instead of the full identifier in two Verilog frontend warnings.

Verilog: use display_name in two warnings

---

regression/verilog/system_verilog_assertion/initial1.desc
regression/verilog/system_verilog_assertion/initial1.sv
src/verilog/parser.y

This moves the Verilog grammar closer to the standard around the rules for assertion statements and module items.

Concurrent assertion statements

---

src/verilog/verilog_expr.h
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h
src/verilog/verilog_typecheck.cpp

This adds typing for the sub-ireps of `verilog_instt`.

Verilog: stengthen typing when using verilog_instt

---

regression/verilog/modules/ports4.desc
regression/verilog/modules/ports4.v
src/verilog/verilog_synthesis.cpp

The parameter is not expanded to its value in the port binding.

Verilog: fix module port binding

---

regression/ebmc/random-traces/long_trace1.desc
regression/ebmc/random-traces/long_trace1.v

This adds a test for randomly generating a trace with 1000 steps.

ebmc: add a test for randomly generating a trace with 1000 steps

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h

The `ns` reference member is already in the base class of `verilog_synthesist`; this removes the duplication.

Verilog: remove duplicate ns member

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h

Use an `exprt` instead of an `mp_integert` to propagate non-numerical constants.

Verilog: Synthesis now uses exprt for propagating constants

---

regression/ebmc/ranking-function/counter_in_module1.desc
src/verilog/verilog_language.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis.h
src/verilog/verilog_synthesis_class.h

We need to synthesise expressions given on the command line in order to support parameters and hierarchical identifiers.

synthesise command-line expressions

---

regression/ebmc/random-traces/long_trace1.random-waveform.desc
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/random_traces.cpp
src/ebmc/random_traces.h

This adds two command-line options `--random-waveform` and `--random-trace`, which print a single random trace to the console.

ebmc: add --random-waveform and --random-trace

---

regression/ebmc/random-traces/counter_with_initial_value.desc
regression/ebmc/random-traces/counter_with_initial_value.v
src/ebmc/random_traces.cpp

`--random-traces` now honors `--waveform`.

ebmc: random traces with waveform output

---

src/ebmc/ebmc_parse_options.cpp
src/trans-netlist/unwind_netlist.cpp
src/trans-word-level/unwind.cpp

The progress output during unwinding is downgraded from `status` to the `progress` verbosity level.

ebmc: Downgrade level of progress output during unwinding

---

src/verilog/verilog_typecheck.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

`genvar_value` now returns the value, instead of writing it to a supplied reference.

Verilog: genvar_value now returns the value

---

src/verilog/parser.y
src/verilog/scanner.l

This is to align the grammar with the System Verilog grammar.

Verilog: rename token for identifiers

---

regression/verilog/string/string_literals1.desc
regression/verilog/string/string_literals1.v
src/verilog/verilog_typecheck_expr.cpp

The conversion of string literals has assumed a binary number represenation.

Verilog: fix string literals

---

src/verilog/parser.y

This introduces the rules for `constant_range`, `indexed_range`, and `part_select_range`, to match IEEE 1800-2017.

Verilog: rules for part select expressions

---

src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

`convert_expr_rec`, and the methods for various expressions, now return a value, instead of changing an expression via a reference.

Verilog: return values during expression type checking

---

regression/ebmc/neural-liveness/counter1.desc
regression/ebmc/ranking-function/counter1.fail.desc
regression/ebmc/ranking-function/counter1.pass.desc
regression/ebmc/ranking-function/counter2.fail.desc
regression/ebmc/ranking-function/counter2.pass.desc
regression/ebmc/ranking-function/counter_in_module1.desc
regression/ebmc/ranking-function/counter_with_reset1.fail.desc
regression/ebmc/ranking-function/counter_with_reset1.pass.desc
regression/ebmc/ranking-function/lexicographic_ranking_function1.desc
regression/verilog/system_verilog_assertion/eventually3.desc
src/verilog/expr2verilog.cpp

This removes parentheses when printing unary SVA operators that have operands that are unary.

ebmc: avoid parentheses in SVA output for unary operators

---

regression/verilog/modules/localparam3.desc
regression/verilog/modules/localparam3.v
src/verilog/parser.y
src/verilog/verilog_elaborate_constants.cpp

This adds support for explicit types for parameters.

Verilog: parameters may be typed

---

regression/ebmc/k-induction/k-induction3.desc
regression/ebmc/k-induction/k-induction3.v
regression/ebmc/k-induction/k-induction5.k-1.desc
regression/ebmc/k-induction/k-induction5.k-3.desc
src/ebmc/k_induction.cpp

Do not perform step case for a property if the base case has failed. Otherwise, wrong results (INCONCLUSIVE or PROVED) may be reported for properties that are known to be REFUTED.

ebmc: bugfix for k-induction

---

src/ebmc/ebmc_base.cpp
src/ebmc/k_induction.cpp
src/ebmc/liveness_to_safety.cpp
src/ebmc/random_traces.cpp
src/ebmc/ranking_function.cpp
src/ebmc/show_trans.cpp
src/ebmc/transition_system.cpp
src/ebmc/transition_system.h

The `trans_expr` in `transition_systemt` is always populated, and does not need to be optional.

ebmc: transition_systemt does not need optional transt

---

regression/ebmc/liveness-to-safety/failing1.k-1.desc
regression/ebmc/liveness-to-safety/failing2.k-6.desc
regression/ebmc/liveness-to-safety/passing1.k-10.desc
regression/ebmc/liveness-to-safety/passing2.k-10.desc
src/ebmc/k_induction.cpp

This enables the combination of liveness to safety translation followed by k-induction.

ebmc: add liveness-to-safety translation to k-induction

---

src/ebmc/report_results.cpp

PROVED is green, INCONCLUSIVE yellow, errors are red.

ebmc: show result status with color

---

src/ic3/ebmc_ic3_interface.hh
src/ic3/m1ain.cc

This changes the interface between the IC3 implementation and ebmc by switching from `ebmc_baset` to directly calling the relevant APIs.

ebmc: simplify IC3/ebmc interface

---

src/verilog/parser.y

This adds the System Verilog grammar rules to allow top-level package items.

Verilog: allow top-level package items

---

regression/ebmc/p-command-line-option/p-command-line-option1.desc
regression/ebmc/p-command-line-option/p-command-line-option1.v
src/ebmc/ebmc_properties.cpp

This sets the message handler, which fixes `-p`.

ebmc: fix -p command line option

---

regression/ebmc/p-command-line-option/p-command-line-option1.desc
src/verilog/scanner.l

The code that handles the two kinds of identifiers (quoted or not) is consolidated in the `IDENTIFIER` macro.

Verilog: consolidate the two kinds of identifiers in the tokenizer

---

regression/ebmc/k-induction/k-induction-unsupported1.desc
regression/ebmc/k-induction/k-induction-unsupported1.sv
src/ebmc/ebmc_error.h
src/ebmc/ebmc_parse_options.cpp
src/ebmc/k_induction.cpp

Return an error when k-induction is given a liveness property.

ebmc: error k-induction when given liveness property

---

src/verilog/parser.y

This renames grammar rules to match System Verilog 1800-2017.

Verilog: grammar for hierarchical_identifier select

---

regression/verilog/functioncall/functioncall1.desc

The test is now marked as CORE.

Verilog: test functioncall1 passes

---

src/verilog/verilog_elaborate_constants.cpp
src/verilog/verilog_types.h

This adds a class for an irep used during Verilog elaboration.

Verilog: introduce to_be_elaborated_typet

---

src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_type.cpp

This adds typechecking for `byte`, `shortint`, `int`, etc.

Verilog: typechecking for all System Verilog integer types

---

regression/verilog/bit-extract/bit-extract3.desc
regression/verilog/bit-extract/bit-extract3.sv
src/verilog/verilog_typecheck_expr.cpp

This removes the error on out-of-bounds bit-extract, to align with the standard.

Verilog: out-of-bounds bit-extract is x or 0

---

regression/verilog/generate/generate-inst1.desc
regression/verilog/generate/generate-inst1.v
regression/verilog/generate/generate-inst2.desc
regression/verilog/generate/generate-inst2.v
src/verilog/parser.y
src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h

When expanding module instances in generate loops the block name must be used to derive a new instance identifier, and derived from that, instantiated identifiers.

Verilog: fix for module instances in generate loops

---

regression/verilog/arrays/array1.desc
regression/verilog/arrays/array1.sv
src/verilog/parser.y
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

System Verilog allows arrays that have a size, as opposed to a range.

Verilog: implement System Verilog arrays with size

---

regression/verilog/modules/parameters8.desc
regression/verilog/modules/parameters8.v

This adds a test that triggers a bug in the module parameterization.

Verilog: KNOWNBUG test for parameter instantiation

---

regression/verilog/functioncall/functioncall5.desc
regression/verilog/functioncall/functioncall5.v
src/verilog/verilog_synthesis.cpp

This adds a KNOWNBUG test for mixed function contexts, and adds location output for the error.

Verilog: KNOWNBUG test for mixed function contexts

---

regression/verilog/modules/parameters8.desc
regression/verilog/modules/parameters8.v
regression/verilog/modules/parameters9.desc
regression/verilog/modules/parameters9.v
src/verilog/verilog_expr.h
src/verilog/verilog_parameterize_module.cpp

This fixes the name generation for parameterized modules when parameter
values are derived from others.

Verilog: fix for derived parameters

---

src/verilog/verilog_typecheck.cpp

This replaces uses of the `error()` message stream by throwing an `errort` exception.

Verilog: use errort in verilog_typecheck.cpp

---

src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp

This introduces a method for accessing the statements in the block.

Verilog: strengthen typing when using verilog_blockt

---

regression/verilog/typedef/typedef2.sv
src/verilog/parser.y

This fixes the name of the scope created for functions.

Verilog: fix scope created for functions

---

src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h

This improves the typing of `verilog_inst_builtint`.

Verilog: introduce verilog_inst_baset

---

src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp

This now returns a vector of declarations, as opposed to a vector of expressions.

Verilog: strengthen typing of verilog_module_sourcet::ports

---

src/ebmc/bmc.cpp

When using `--outfile`, still invoke the solver to finish any solver-specific conversion.

ebmc: call solver when using --outfile

---

src/verilog/verilog_elaborate_constants.cpp

This replaces a low-level type constructor by the one provided for the purpose.

Verilog: use to_be_elaborated_typet

---

regression/verilog/modules/port_not_declared.desc
regression/verilog/modules/port_not_declared.v

This adds a test to check error handling in case of a malformed port declaration.

Verilog: add test for module with undeclared port

---

regression/ebmc/BDD/BDD_SVA1.desc
regression/ebmc/k-induction/k-induction-unsupported1.desc
regression/ebmc/k-induction/k-induction-unsupported2.desc
regression/ebmc/k-induction/k-induction-unsupported2.sv
src/ebmc/bdd_engine.cpp
src/ebmc/bmc.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h
src/ebmc/k_induction.cpp

Instead of reporting an unhelpful `UNKNOWN`, the user is now told explicitly
that the property is not supported.

ebmc: error when BDD engine is given unsupported property

---

regression/verilog/modules/ports3.v
regression/verilog/modules/ports6.desc
regression/verilog/modules/ports6.v
src/verilog/verilog_elaborate_constants.cpp
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_typecheck.h

This moves the creation of the module port symbols from `verilog_interfaces` to `verilog_elaborate_constants`.  The benefit is that elaboration time constants may now depend on the type of module ports.

Verilog: collect port symbols during elaboration

---

src/verilog/verilog_elaborate_constants.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp

This improves typing in the Verilog frontend by avoiding general expressions.

Verilog: use declaratort

---

src/verilog/parser.y
src/verilog/verilog_elaborate_constants.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp

This replaces the use of an equality expression for declarators with initializers by the declarator class.

Verilog: replace equality by declarator class

---

src/verilog/parser.y
src/verilog/verilog_elaborate_constants.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp

This replaces the use of `symbol_exprt` as a declarator in all declarations by the dedicated type `declaratort`.

Verilog: use declaratort instead of symbol_exprt

---

src/verilog/verilog_expr.h
src/verilog/verilog_generate.cpp
src/verilog/verilog_typecheck.h

This uses types stronger than `exprt` for Verilog generate constructs.

Verilog: strengthen typing for generate constructs

---

src/verilog/verilog_interfaces.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h

To clarify the side effect of the `typecheck()` method, the value of the module symbol is now set there.

Verilog: clarify method signatures

---

src/verilog/parser.y
src/verilog/verilog_elaborate.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_generate.cpp
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_typecheck.cpp

Clean up terminology: identifier (with scope) vs. base name (no scope)

Verilog: clean-up identifier vs. base_name

---

regression/verilog/elaboration/var_bits.desc
src/verilog/verilog_elaborate.cpp
src/verilog/verilog_interfaces.cpp

This moves the creation of symbols for var/reg identifiers from verilog_interfaces to the elaboration phase.

Verilog: elaborate var/reg

---

regression/verilog/typedef/typedef_name_collision1.desc
src/verilog/parser.y
src/verilog/verilog_expr.h
src/verilog/verilog_interfaces.cpp

This normalises the use for `ID_identifier` vs. `ID_base_name` vs. `ID_C_base_name` in the Verilog parser.

Verilog: clean up base_name vs identifier in declarators

---

.github/workflows/pull-request-checks.yaml
regression/verilog/Makefile
regression/verilog/assignment-to-concatenation/test.desc
regression/verilog/assignment-to-range1/test.desc
regression/verilog/bit-extract/bit-extract1.desc
regression/verilog/bit-extract/bit-extract2.desc
regression/verilog/case/case3.desc
regression/verilog/case/case4.desc
regression/verilog/functioncall/functioncall3.desc
regression/verilog/generate/generate-for2.desc
regression/verilog/generate/generate-reg1.desc
regression/verilog/generate1/test.desc
regression/verilog/indexed-part-select1/test.desc
regression/verilog/modules/ports2.desc
regression/verilog/multiple_assign1/test.desc
regression/verilog/nondet1/test.desc
regression/verilog/replication/replication1.desc
regression/verilog/replication/replication1.v
regression/verilog/replication1/test.desc
regression/verilog/system_verilog_assertion/system_verilog_assertion3.desc
src/verilog/verilog_typecheck_expr.cpp

The SystemVerilog 1800-2017 standard explicitly allows replications with count zero.

Verilog: zero-count replication

---

src/util/ebmc_util.h
src/verilog/verilog_synthesis.cpp

This removes the last two uses of `binary_to_hex`.

Verilog: remove binary_to_hex

---

src/ebmc/random_traces.cpp
src/ebmc/random_traces.h

The `random_tracest` class now offers a callback instead of specific mechanisms for outputting the generated traces.

random_tracest now offers callback

---

regression/ebmc/traces/numbered1.desc
regression/ebmc/traces/numbered1.smv
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/random_traces.cpp
src/ebmc/report_results.cpp
src/trans-netlist/trans_trace.cpp
src/trans-netlist/trans_trace.h

This introduces a new trace format designed for checking values of particular state variables in particular time frames.

ebmc: traces with identifiers numbered with time frames

---

regression/verilog/data-types/enum_initializers1.desc
src/verilog/verilog_typecheck_expr.cpp

Most Verilog operators decay enum-typed arguments to their base type.

Verilog: enums decay when used in relational/arithmetic operators

---

regression/verilog/enums/enum1.desc
regression/verilog/enums/enum2.desc
regression/verilog/enums/enum_base_type2.desc
regression/verilog/enums/enum_initializers1.desc
regression/verilog/enums/enum_initializers2.desc
regression/verilog/enums/enum_initializers2.sv
regression/verilog/enums/enum_initializers3.desc
src/verilog/verilog_elaborate.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_type.cpp
src/verilog/verilog_types.h

This postpones the conversion of enum base types and enum initializers to enable them to depend on other elaboration-time constants.

Verilog: enum constants may depend on elaboration-time constants

---

regression/verilog/data-types/wire_must_be_fourvalued.desc
regression/verilog/data-types/wire_must_be_fourvalued.sv

SystemVerilog requires wires to have four-valued data types.  We must error when given a binary data type.

Verilog: KNOWNBUG test for a wire with binary data type

---

regression/verilog/typedef/global_typedef.desc
regression/verilog/typedef/global_typedef.sv

These are an extension used by the VIS model checker, and are not supported by SystemVerilog.

Verilog: KNOWNBUG test for global-scoped typedefs

---

src/verilog/parser.y

This moves the `concurrent_assertion_statement` rule from `statement_item` to `procedural_assertion_statement`, as in 1800-2017.

Verilog: move concurrent_assertion_statement

---

src/smvlang/parser.y

This rewrites a number of rules in the SMV language grammar to make them left recursive instead of right recursive.  This avoids using a linear amount of space on the Bison parser stack, and hence, enables parsing long SMV files without triggering the "memory exhausted" error.
Fixes #233.

SMV frontend: make rules left recursive

---

src/trans-netlist/Makefile
src/trans-netlist/aig.cpp
src/trans-netlist/aig.h
src/trans-netlist/aig_terminals.cpp
src/trans-netlist/aig_terminals.h
src/trans-netlist/ldg.cpp

This extracts a rarely used method from aigt into a separate file.

netlists: move get_terminals into separate file

---

src/verilog/verilog_expr.h
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h

SystemVerilog assertions and assumptions can be module items (called concurrent assertions/assumptions) or statements.  While the syntax for the two variants is similar, there are differences.  This commit splits the ireps for the two variants.

Verilog: split assert/assume module items and statements

---

regression/ebmc/smv/bdd_unsupported_property.desc
regression/ebmc/smv/bdd_unsupported_property.smv
regression/ebmc/smv/bmc_unsupported_property1.desc
regression/ebmc/smv/bmc_unsupported_property1.smv
regression/ebmc/smv/bmc_unsupported_property2.desc
regression/ebmc/smv/bmc_unsupported_property2.smv
src/ebmc/bmc.cpp
src/trans-netlist/unwind_netlist.cpp
src/trans-word-level/property.cpp
src/trans-word-level/property.h

This changes the behavior when an unsupported property is given to the BMC engine.  Instead of exiting, this is now reported in the property list. Supported properties are still checked.

ebmc: reporting when unsupported property is given

---

src/verilog/verilog_elaborate.cpp
src/verilog/verilog_generate.cpp
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_interpreter.cpp
src/verilog/verilog_parameterize_module.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_base.cpp
src/verilog/verilog_typecheck_type.cpp

This replaces instances of `throw 0` by `errort()`.

Verilog: use `errort()` instead of `throw 0`

---

src/verilog/parser.y

This renames `module_port_declaration` to `ansi_port_declaration`, to match SystemVerilog 1800-2017.

Verilog: ansi_port_declaration

---

regression/verilog/modules/input_and_wire.desc
regression/verilog/modules/input_and_wire.v

This adds tests for `input wire` ports, and for ANSI-style `output wire` ports.

Verilog: extend tests for module ports

---

regression/verilog/modules/parameter_ports3.desc
regression/verilog/modules/parameter_ports3.v
src/verilog/parser.y

This adds support for `localparam` parameter ports.

Verilog: localparam parameter ports

---

src/verilog/parser.y

This renames the rule to match SystemVerilog 1800-2017, and makes it optional, as in the standard.

Verilog: parameter_value_assignment is optional

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck_base.cpp
src/verilog/verilog_typecheck_base.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_types.h

This avoids checking for overflows when adding up widths.

Verilog: `get_width` now returns `mp_integer`

---

src/verilog/parser.y
src/verilog/scanner.l

This add the System Verilog class scope operator `::`.

Verilog: class scope operator

---

src/verilog/verilog_elaborate.cpp
src/verilog/verilog_expr.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_typecheck_type.cpp

This removes the duplication of the code that merges the declarator type (an unpacked array type) with the type in the declaration by introducing a helper method.

Verilog: helper to merge declaration and declarator type

---

regression/verilog/synthesis/continuous_assignment_to_variable.desc
regression/verilog/synthesis/continuous_assignment_to_variable.v
src/verilog/verilog_typecheck.cpp

SystemVerilog allows (non-procedural) continuous assignments to variables.

Verilog: continuous assignments to variables

---

src/trans-word-level/property.cpp

The property encoding interface is changed to return a timeframe/handle pair, instead of just a condition per timeframe.
This allows determining the appropriate size of the counterexample trace.

BMC: encode properties using timeframe/handle pair

---

regression/ebmc/smv/smv_ltlspec3.desc
regression/ebmc/smv/smv_ltlspec3.smv
src/temporal-logic/temporal_expr.h
src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/property.cpp

This adds support for the LTL `X` operator to the BMC engine.

BMC: add support for LTL X operator

---

regression/verilog/SVA/sequence1.desc
regression/verilog/SVA/sequence1.sv

This adds a test that triggers a case where too few states are shown in the counterexample.

ebmc: KNOWNBUG test for a bounded sequence expression

---

src/ebmc/bdd_engine.cpp
src/ebmc/bmc.cpp
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h
src/ebmc/k_induction.cpp
src/ebmc/liveness_to_safety.cpp
src/ebmc/neural_liveness.cpp
src/ebmc/ranking_function.cpp
src/ic3/r1ead_input.cc
src/temporal-logic/Makefile
src/temporal-logic/normalize_property.cpp
src/temporal-logic/normalize_property.h
src/verilog/verilog_synthesis.cpp

This introduces a pass during which the given property is 'normalized', using heuristic rewrites, with the goal to reduce the burden of a large number of redundant case-splits in each backend.

ebmc: normalize properties

---

src/Makefile

hw-cbmc needs `temporal-logic.dir`, and this adds a dependency in the `Makefile`.

add dependency on temporal-logic.dir

---

regression/verilog/SVA/cover1.desc
src/ebmc/bdd_engine.cpp
src/ebmc/bmc.cpp
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h
src/ebmc/report_results.cpp
src/temporal-logic/temporal_logic.cpp
src/temporal-logic/temporal_logic.h

This adds support for SVA cover properties to the BMC engine.

Implement SVA cover in BMC

---

src/verilog/verilog_typecheck_expr.cpp

This restores code accidentally commented out in
4b56ef0ed71fba918d0db55f69dab80df8f268f7.

fixup for #432

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This prevents premature optimisation by expanding `$ND` during synthesis.

Verilog: expand $ND during synthesis, not typechecking

---

regression/verilog/preprocessor/include_file2.vh
regression/verilog/preprocessor/not_found2.desc
regression/verilog/preprocessor/not_found2.v
src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h

This adds the include directive that does not search the directory of the file that contains the include directive.

Verilog: add `include <some_file>

---

regression/ebmc/smv/bmc_unsupported_property3.desc
regression/ebmc/smv/bmc_unsupported_property3.smv
src/ebmc/ebmc_base.cpp
src/trans-netlist/unwind_netlist.cpp
src/trans-netlist/unwind_netlist.h

The netlist-based BMC implementation now reports a proper error in the report when given an unsupported property.

netlist-BMC now gives error for unsupported properties

---

regression/ebmc/smv/smv_ltlspec3.desc
regression/ebmc/traces/numbered1.desc
regression/verilog/SVA/cover1.desc
src/ebmc/report_results.cpp

This enables writing tests that check the length of the witness trace.

numbered trace output now includes number of states

---

regression/verilog/preprocessor/define1.desc
regression/verilog/preprocessor/define1.v
src/verilog/verilog_preprocessor.cpp

Verilog allows whitespace between the macro identifier and the parentheses.

Verilog: allow whitespace between macro and arguments

---

regression/verilog/preprocessor/in_subdir.desc
regression/verilog/preprocessor/include2.desc
regression/verilog/preprocessor/subdir/in_subdir.v
src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h

This adds a KNOWNBUG test for the case where a Verilog file is in a subdirectory and a local include is in the same subdirectory.

Verilog: fix for file in subdirectory with local include

---

src/verilog/parser.y

This moves the rule `net_port_type` and `net_type_opt` to Section A.2.2.1, as in SystemVerilog 1800-2017.

Verilog: move net_port_type rule

---

src/ebmc/Makefile
src/ebmc/ebmc_languages.cpp

This removes duplicates in the object list, and removes the check whether the verilog directory exists.

ebmc: cleanup Makefile

---

src/Makefile

This restricts the build of the CBMC dependency to those modules that are used by ebmc.

only build parts of CBMC that are used

---

regression/verilog/preprocessor/double_backtick1.desc
regression/verilog/preprocessor/double_backtick1.sv
src/verilog/verilog_preprocessor.cpp

This adds the double-backtick to the Verilog preprocessor.

Verilog: double-backtick

---

regression/ebmc/BDD/BDD_SVA1.desc
src/temporal-logic/temporal_logic.cpp
src/trans-netlist/netlist.cpp
src/trans-netlist/netlist.h
src/trans-netlist/trans_to_netlist.cpp

The conversion to netlist now includes the properties, which are then reproduced in the SMV output.

SMV netlist output now includes temporal logic properties

---

regression/verilog/SVA/unbounded1.desc
regression/verilog/SVA/unbounded1.sv
src/verilog/parser.y

This adds support for Verilog parameters that have value `$`, signalling an unbounded range.

Verilog: parameters with value $

---

regression/verilog/const/const1.desc
regression/verilog/const/const1.sv
src/verilog/parser.y

This adds the grammar rules for `const` variable declarations.

Verilog: const variable declarations

---

regression/verilog/modules/inout_and_variable.desc
regression/verilog/modules/inout_and_variable.v
src/verilog/verilog_expr.h
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h

This class documents an existing expression type in the Verilog frontend.

Introduce `verilog_inst_baset::named_port_connectiont`

---

regression/verilog/modules/type_parameters1.desc
regression/verilog/modules/type_parameters1.sv
src/verilog/parser.y
src/verilog/verilog_elaborate.cpp
src/verilog/verilog_typecheck_type.cpp

This adds support for `localparam` and `parameter` declarations that declare a type.

SystemVerilog: type parameters

---

regression/verilog/SVA/immediate2.desc
regression/verilog/SVA/immediate2.sv
src/verilog/verilog_elaborate.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h
src/verilog/verilog_typecheck.cpp

This fixes the bug that procedural `assert`/`assume`/`cover` statements do not consider the execution guard.

Verilog: procedural assert/assume/cover are guarded

---

regression/ebmc/SVA-LTL/freeze.desc
regression/ebmc/SVA-LTL/freeze.sv
src/trans-word-level/property.cpp

This is a fixup for 0158a8b102478b57ac19e217744bf8432.  This has returned a conjunction of handles instead of a handle.  The conjunction isn't frozen, and hence failed when using incremental SAT.

fixup: timeframe handles must be frozen

---

regression/ebmc/BDD/GF1.desc
regression/ebmc/BDD/GF1.smv

Minimal example for a bug in the BDD engine when doing `G` `F` properties.

BDD engine: KNOWNBUG for G F properties

---

src/trans-netlist/trans_to_netlist.cpp

The generation of netlists from transition system now uses the state constraint facility of the netlist data structure for state constraints, as opposed to adding everything as a transition constraint.
This fixes cases where analyzers over-approximate the model semantics.

state invariants are now converted into AIG state constraints

---

src/trans-netlist/netlist.cpp

The output of `--show-netlist` now includes the AIG constraints.

netlist output now includes AIG constraints

---

regression/ebmc/smv/module1.desc
regression/ebmc/smv/module1.smv
src/trans-word-level/property.cpp

BMC on a property with a top-level conjunction now splits up conjunctions, to form separate sets of obligations.

BMC now splits up top-level conjunction

---

regression/ebmc/smv/module1.desc

Fixes a test that was newly introduced in 53367541f with fde07ab being done (and now merged) independently.

fixup! SMV frontend: strip main:: from property pretty names

---

src/verilog/parser.y

This
1) moves the rule `list_of_port_declarations` to Sec A.1.3, as in 1800-2017.
2) moves the rules `module_port_inout_declaration`,
`module_port_input_declaration` and `module_port_output_declaration` into the rule `ansi_port_declaration`, as in 1800-2017.

Verilog: cleanup `ansi_port_declaration` rule

---

regression/ebmc/Makefile
regression/hw-cbmc/Makefile
regression/verilog/Makefile
regression/vhdl/Makefile

To better understand CI failures, `-p` results in all output of failing tests to be printed. While at it, also enable exit-code requirements (`-e`) to make sure all test specifications include those.

Tests: enable exit-code requirement and output on failure

---

regression/ebmc/BDD/AF1.smv
regression/ebmc/BDD/AF2.smv
regression/ebmc/BDD/AG1.smv
regression/ebmc/BDD/AG2.smv
regression/ebmc/BDD/AU1.smv
regression/ebmc/BDD/AX1.smv
regression/ebmc/BDD/BDD1.desc
regression/ebmc/BDD/BDD1.smv
regression/ebmc/BDD/EF1.smv
regression/ebmc/BDD/EF2.smv
regression/ebmc/BDD/EG1.smv
regression/ebmc/BDD/EG2.smv
regression/ebmc/BDD/EX1.smv
regression/ebmc/BDD/EX2.smv
regression/ebmc/BDD/just_p.smv
regression/ebmc/range_type/range_type1.smv
regression/ebmc/range_type/range_type4.smv
regression/ebmc/range_type/range_type5.smv
regression/ebmc/smv/bdd_unsupported_property.smv
regression/ebmc/smv/bmc_unsupported_property1.smv
regression/ebmc/smv/bmc_unsupported_property2.smv
regression/ebmc/smv/bmc_unsupported_property3.smv
regression/ebmc/smv/initial1.smv
regression/ebmc/smv/module1.smv
regression/ebmc/smv/smv2.smv
regression/ebmc/smv/smv3.smv
regression/ebmc/smv/smv_ltlspec1.smv
regression/ebmc/smv/smv_ltlspec2.smv
regression/ebmc/smv/smv_ltlspec3.smv

Since version 2.5.1, NuSMV no longer performs an implicit conversion from integers to booleans.  This replaces `1` by `TRUE` and `0` by `FALSE` to enable NuSMV to read our tests.

SMV tests: use TRUE and FALSE

---

src/verilog/parser.y

This introduces the `property_spec` rule to the SVA grammar, to match 1800-2017.

SystemVerilog: property_spec rule

---

regression/ebmc/ranking-function/counter2.fail.desc
src/ebmc/neural_liveness.cpp
src/ebmc/ranking_function.cpp
src/ebmc/ranking_function.h

This records the satisfying assignment when checking a ranking function and outputs it as a two-step trace, to enable debugging the candidate ranking function.

ebmc: generate a witness that a given candidate isn't a ranking function

---

regression/ebmc/ic3/not_supported1.desc
regression/ebmc/ic3/not_supported1.sv
src/ic3/m1ain.cc

The IC3 engine now reports an appropriate error message when given an unsupported property.

EBMC: give error message when unsupported property is passed to IC3

---

src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h
src/ebmc/k_induction.cpp
src/ebmc/neural_liveness.cpp
src/ebmc/ranking_function.cpp
src/ic3/m1ain.cc

This consolidates the logic for determining the tool exit code in one place, to achieve consistency.

introduce ebmc_propertiest::exit_code

---

regression/ebmc/traces/disjunction1.desc
regression/ebmc/traces/disjunction1.smv
src/trans-word-level/property.cpp

Given a property a ∨ b with obligations at timeframe l and m, generate the obligation for the disjunction at timeframe max{l, m}.

trace length for disjunctive properties

---

regression/verilog/synthesis/always_comb3.desc
regression/verilog/synthesis/always_comb3.sv
src/verilog/verilog_synthesis.cpp

This fixes the synthesis of the RHS when using SystemVerilog's `always_comb`.

Verilog: fix always_comb synthesis

---

regression/verilog/system-functions/past2.desc
src/trans-netlist/instantiate_netlist.cpp

There is now a clear error message when `$past` is not yet supported.

Verilog: error when using $past with an AIG-based engine

---

src/trans-netlist/var_map.cpp

This replaces legacy error reporting via `std::cerr` and `assert(...)` by throwing an `ebmc_errort()` exception.

ebmc var_map: use ebmc_errort instead of assert(...)

---

regression/verilog/synthesis/continuous_assignment_to_variable_systemverilog.desc
regression/verilog/synthesis/continuous_assignment_to_variable_systemverilog.sv
regression/verilog/synthesis/continuous_assignment_to_variable_verilog.desc
regression/verilog/synthesis/continuous_assignment_to_variable_verilog.v

Continous assignments to variables are allowed in SystemVerilog, but not Verilog.

Verilog: KNOWNBUG test for continuous assignments to variables

---

src/verilog/Makefile
src/verilog/scanner.l
src/verilog/verilog_language.cpp
src/verilog/verilog_parser.h
src/verilog/verilog_standard.cpp
src/verilog/verilog_standard.h

This adds an enum that distinguishes the various Verilog standards and dialects.

Verilog: add verilog_standardt

---

regression/verilog/system-functions/stable-rose-fell-changed1.desc
regression/verilog/system-functions/stable-rose-fell-changed1.sv
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck_expr.cpp

This adds `$stable`, `$rose`, `$fell`, `$changed` to the SystemVerilog frontend.

SystemVerilog: $stable, $rose, $fell, $changed

---

regression/verilog/synthesis/part_select1.desc
regression/verilog/synthesis/part_select1.sv
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_expr.cpp

The Verilog frontend translates Verilog part select expressions into extractbits expressions.  This is moved from the typechecker to the synthesis phase.

Verilog: move translation of part select expressions into synthesis phase

---

regression/ebmc/traces/verilog1.desc
regression/ebmc/traces/verilog1.v
src/trans-word-level/trans_trace_word_level.cpp

This adds the values of macro symbols (`parameter`, `localparam`, etc.) to the BMC trace.

BMC: include macros in trace

---

regression/ebmc/random-traces/initial_state1.desc
regression/ebmc/random-traces/initial_state1.v
src/ebmc/random_traces.cpp

Instead of relying on the user to initialize the state, we use random constraints.

random traces: set random initial state

---

src/verilog/scanner.l
src/verilog/verilog_language.cpp
src/verilog/verilog_language.h
src/verilog/verilog_parameterize_module.cpp
src/verilog/verilog_parse_tree.h
src/verilog/verilog_parser.cpp
src/verilog/verilog_parser.h
src/verilog/verilog_standard.h
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis.h
src/verilog/verilog_synthesis_class.h
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h
src/verilog/verilog_typecheck_base.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This tracks the configured Verilog standard in the parse tree data structure, to support mixed-version models.

Verilog: standard version now tracked in parse tree

---

regression/ebmc/traces/vcd1.desc
regression/ebmc/traces/vcd1.v
src/ebmc/random_traces.cpp
src/trans-netlist/trans_trace.cpp

This implements scoped reference names for `$var` sections in VCD output, as defined in 1800-2017.
The `--random-trace` flow now accepts `-` as filename for VCD output, to enable checking the VCD output in tests.

VCD output: scoped reference names

---

regression/ebmc/neural-liveness/counter1.desc
regression/ebmc/neural-liveness/live_signal1.desc
regression/ebmc/random-traces/boolean1.desc
regression/ebmc/random-traces/bv1.desc
regression/ebmc/random-traces/counter_with_initial_value.desc
regression/ebmc/random-traces/long_trace1.desc
regression/ebmc/random-traces/with_submodule.desc
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/neural_liveness.cpp
src/ebmc/random_traces.cpp

This renames the option --number-of-traces to --traces.  This is consistent with the names of the two other options that specify numbers (--trace-steps, --bound).

--number-of-traces --> --traces

---

src/ebmc/liveness_to_safety.cpp
src/ebmc/random_traces.cpp
src/ebmc/transition_system.cpp
src/ebmc/transition_system.h

This extracts to replicated methods that identify the inputs and the state variables of the transition system.

extract `transition_systemt::inputs` and `::state_variables`

---

regression/verilog/SVA/sequence2.desc
regression/verilog/SVA/sequence2.sv
src/temporal-logic/normalize_property.cpp
src/verilog/sva_expr.h

This rewrites `##[i:$]` to LTL, enabling the back-end to generate counterexamples of the correct length.

Verilog: normalize `##[i:$]`

---

regression/verilog/SVA/sequence1.desc
src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/instantiate_word_level.h
src/trans-word-level/property.cpp

The word-level property instantiation now returns the largest timeframe used, in addition to the instantiated property.
This enables making the counterexample have the right length.

property instantiation now returns largest timeframe used

---

regression/verilog/SVA/sequence3.desc

This adds the `.desc` file that was forgotten in #529.

Fixup #529: add missing .desc file

---

regression/verilog/SVA/nexttime1.desc
regression/verilog/SVA/nexttime1.sv
src/temporal-logic/negate_property.cpp
src/temporal-logic/normalize_property.cpp
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/parser.y
src/verilog/sva_expr.h
src/verilog/verilog_typecheck_expr.cpp

This adds front-end support for indexed `nexttime` and `s_nexttime`.

Verilog SVA: indexed `nexttime` and `s_nexttime`

---

regression/verilog/SVA/always_with_range1.desc
regression/verilog/SVA/cover2.desc
regression/verilog/SVA/initial1.desc
regression/verilog/SVA/initial1.sv
regression/verilog/SVA/sequence1.desc
regression/verilog/SVA/sequence2.desc
regression/verilog/SVA/sequence3.desc
src/verilog/verilog_typecheck.cpp

This enables identifying the statement in the verification result report.

Verilog: stick statement label onto `assert`/`assume`/`cover`

---

.github/workflows/ebmc-release.yaml

This fixes a typo ('seperator' -> 'separator') copied from the CBMC repo.

fix typo in release workflow

---

.github/workflows/ebmc-packages.yaml

This changes the trigger, in the hope it will get run when creating a release, and adds a CentOS 8 rpm.

CI: ebmc-packages workflow fixes

---

.github/workflows/ebmc-release.yaml

* `chown root:root` for making the .deb needs `sudo`
* `bruceadams/get-release` needs the `GITHUB_TOKEN`
* `actions/upload-release-asset` needs the `GITHUB_TOKEN`
* `rpmbuild` does not like an empty Requires tag

Fix ebmc release workflow

---

src/ic3/Makefile

* use $(LIBEXT) instead of hard-wiring .a
* use $(LINKLIB) instead of hard-wiring ar and ranlib

IC3 Makefile

---

.github/workflows/pull-request-checks.yaml

* increases number of build processes from 2 to 4 for Linux jobs
* increases number of build processes from 2 to 3 for macOS job
* increases macOS version from 12 to 14

CI: bump vCPU use and macOS version

---

.github/workflows/pull-request-checks.yaml
src/ic3/minisat/minisat/utils/System.cc

This adds a build with `emcc` as a CI PR job.

CI: add emscripten job

---

src/verilog/verilog_typecheck_base.cpp
src/verilog/verilog_typecheck_base.h
src/verilog/verilog_typecheck_expr.cpp

This replaces `verilog_typecheck_exprt::bits_rec` by an invocation to `verilog_typecheck_baset::get_width_opt`.

Verilog: consolidate code that computes width of given type

---

src/ebmc/output_verilog.cpp
src/trans-netlist/aig_prop.h
src/trans-netlist/trans_to_netlist.cpp
src/trans-word-level/counterexample_word_level.cpp
src/trans-word-level/instantiate_word_level.cpp
src/verilog/verilog_typecheck_base.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This replaces uses of the `assert(...)` macro by suitable alternatives, or removes redundant assertions.

replace `assert(...)`

---

.github/workflows/ebmc-release.yaml

This adds the architecture name (amd64) to the file name of the .deb file built by the release process.

include architecture (amd64) in .deb file

---

regression/verilog/structs/structs1.desc
regression/verilog/structs/structs1.sv
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h

SystemVerilog allows converting bit-vectors to packed structs and vice versa.

Verilog: implement bit-vector to struct conversion

---

regression/ebmc/CLI/json-properties.desc
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h
src/ebmc/liveness_to_safety.cpp
src/ebmc/report_results.cpp
src/ebmc/show_properties.cpp
src/smvlang/smv_typecheck.cpp
src/verilog/verilog_synthesis.cpp

This moves the generation of the property description into the front-end, which will enable doing lowering or model instrumentation in the front-end while displaying the property as given in the source language.

Property description now taken from front-end

---

regression/verilog/SVA/immediate1.desc
regression/verilog/SVA/immediate1.sv

This adds a test for an immediate SystemVerilog assertion that is guarded by an `if` statement.

Verilog: add test for conditional immediate assertion

---

.github/workflows/syntax-checks.yaml

This uprades the CI formatting check from clang-format-11 to -15.

CI: bump clang-format to version 15

---

regression/verilog/system-functions/array_functions1.desc
regression/verilog/system-functions/array_functions1.sv
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This adds five system functions that provide information about array types.

Verilog: `$low`, `$high`, `$increment`, `$left`, `$right`

---

src/verilog/parser.y
src/verilog/verilog_parse_tree.cpp
src/verilog/verilog_parse_tree.h

SystemVerilog allows any `package_item` at the top level of the file.  This extends the parse tree to store these, generalising from typedefs, which are package_items.

Verilog: parse tree now stores package_items

---

regression/ebmc/CLI/json-modules.desc
regression/ebmc/CLI/json-modules.v
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/transition_system.cpp
src/trans-word-level/show_modules.cpp
src/trans-word-level/show_modules.h

This adds `--json-modules`, to get a JSON array with all the modules.

JSON output for the modules

---

src/ebmc/Makefile
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_error.h
src/ebmc/neural_liveness.cpp
src/ebmc/output_file.cpp
src/ebmc/output_file.h
src/ebmc/random_traces.cpp
src/ebmc/report_results.cpp
src/ebmc/show_properties.cpp
src/ebmc/show_trans.cpp
src/ebmc/transition_system.cpp

This introduces a new class `output_filet`, which
* given a filename, opens the file for writing, and provides an `std::ostream` for it; if this fails, an appropriate exception is thrown.
* given "-", provides a pointer to `std::cout`

introduce output_filet

---

regression/ebmc/netlist/netlist-trace2.desc
regression/ebmc/netlist/netlist-trace2.sv
src/trans-netlist/trans_to_netlist.cpp

When generating the AIG, the conversion adds new symbols for the next-state value if none is given.  These new symbols now have a mode, and a fresh identifier is generated for each bit, to ensure that the type (bool) is consistent with the variable map.

AIG engine: fix for new symbols for fresh inputs

---

regression/verilog/SVA/immediate1.desc
regression/verilog/SVA/immediate2.desc
regression/verilog/SVA/initial2.desc
regression/verilog/SVA/named_property1.desc
regression/verilog/SVA/unbounded1.desc
regression/verilog/enums/enum4.desc
regression/verilog/enums/enum_base_type1.desc
regression/verilog/enums/enum_base_type2.desc
regression/verilog/expressions/concatenation2.desc
regression/verilog/expressions/static_cast1.desc
regression/verilog/modules/type_parameters1.desc
regression/verilog/structs/structs1.desc
regression/verilog/system-functions/array_functions1.desc
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/verilog_synthesis.cpp

This generates the property description from the expression prior to synthesis, which is closer to the Verilog source code.

Verilog: generate property description prior to expression synthesis

---

regression/ebmc/traces/json1.desc
regression/ebmc/traces/json1.v
src/trans-netlist/trans_trace.cpp

* type is now lhs_type to avoid the ambiguity between the lhs symbol and the full lhs.
* assignments are now actually added
* The trace ends when the property is violated
* The new member state_var indicates whether the assignment is to a state variable or not.

fixes for JSON traces

---

.github/workflows/ebmc-release.yaml

This
a) fixes the ccache for the x64 Debian/Ubuntu release, and
b) adds a WASM release build using emscripten.

add WASM release

---

src/verilog/parser.y

This introduces the `assertion_item` rule, and moves the rules for `assertion_item_declaration` into the right place, following 1800-2017.

SystemVerilog: align assertion-related rules with 1800-2017

---

regression/verilog/case/case3.v
regression/verilog/case/case4.v
regression/verilog/expressions/concatenation3.desc
regression/verilog/expressions/concatenation3.sv
src/verilog/aval_bval_encoding.cpp
src/verilog/aval_bval_encoding.h
src/verilog/verilog_synthesis.cpp

This adds lowering for the concatenation of aval/bval encoded bit-vectors.

Verilog: lowering for concatenation of aval/bval encoded vectors

---

regression/verilog/expressions/equality2.desc
regression/verilog/expressions/equality2.v
src/verilog/aval_bval_encoding.cpp
src/verilog/verilog_synthesis.cpp

This adds support for the lowering of typecasts from 2-valued bit-vectors to aval/bval encoded bit-vectors.

cast from 2-valued to aval/bval 4-valued vectors

---

.github/workflows/pull-request-checks.yaml
benchmarking/hwmcc08.sh

This runs the HWMCC 2008 competition benchmarks in CI, using the results by abc as expected outcome.

ebmc: benchmarking in CI

---

src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h

Using `std::filesystem::path` instead of `std::string` avoids conversion from utf-16 to utf-8 and back on Windows.

use std::filesystem::path instead of std::string

---

src/ebmc/ebmc_error.h
src/verilog/verilog_preprocessor_error.h

C++11 15.1 §5 requires that objects that are thrown have an accessible copy/move constructor and a destructor.
This adds an explicit copy constructor to a few classes where the compiler cannot build the default copy constructor.

copy constructors for exception classes

---

src/verilog/verilog_expr.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_language.cpp
src/verilog/verilog_module.cpp
src/verilog/verilog_module.h
src/verilog/verilog_parse_tree.cpp
src/verilog/verilog_parse_tree.h
src/verilog/verilog_typecheck.cpp

This strengthens the typing in the code that does the iterating.

Verilog: use verilog_module_sourcet to discover instantiated modules

---

regression/ebmc/BDD/AU1.desc
regression/ebmc/BDD/AU1.smv
src/smvlang/expr2smv.cpp
src/smvlang/parser.y
src/smvlang/smv_typecheck.cpp

This adds both parsing and typechecking for the CTL operators AR, ER, AU, EU to the SMV frontend.

SMV: parsing and type checking for CTL AR, ER, AU, EU

---

regression/verilog/system-functions/countones1.desc
regression/verilog/system-functions/countones1.sv
regression/verilog/system-functions/countones2.desc
regression/verilog/system-functions/countones2.sv
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_types.h

This adds the SystemVerilog system function `$countones` (IEEE 1800-2017 20.9).

SystemVerilog: $countones

---

regression/verilog/modules/decoder1.desc
regression/verilog/modules/decoder1.sv

Since Verilog 2005 recursive module instantiation is explicitly allowed. This adds a KNOWNBUG test for this.

Verilog: KNOWNBUG test for recursive module instantiation

---

regression/verilog/modules/error_first_line1.desc
regression/verilog/modules/error_first_line1.v

Given an input file without newline, the error message is missing the line number.

Verilog: KNOWNBUG test for input file without newline

---

regression/verilog/directives/default_nettype1.desc
regression/verilog/directives/default_nettype1.sv
src/verilog/scanner.l
src/verilog/verilog_preprocessor.cpp

The preprocessor now passes default_nettype to the parser.  The parser ignores it for now.

SystemVerilog: ignore default_nettype directive

---

regression/verilog/enums/enum1.aig.desc
src/trans-netlist/trans_to_netlist.cpp

This prevents passing SystemVerilog enums to the decision procedure, which causes an error.
Fixes #623.

Netlist conversion: do not convert types

---

regression/verilog/preprocessor/cmdline_define1.desc
regression/verilog/preprocessor/cmdline_define1.v
regression/verilog/preprocessor/cmdline_define2.desc
regression/verilog/preprocessor/cmdline_define2.v
src/ebmc/ebmc_parse_options.h
src/ebmc/transition_system.cpp
src/verilog/verilog_language.cpp
src/verilog/verilog_language.h
src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h
src/verilog/verilog_preprocessor_tokenizer.cpp
src/verilog/verilog_preprocessor_tokenizer.h

This allows setting SystemVerilog preprocessor defines on the command line with `-D`.

Verilog: set defines on command line

---

src/verilog/parser.y

This moves the grammar rules for expressions into Section A.8.3, as in SystemVerilog 1800-2017.

SystemVerilog: move expression grammar rules to Sec A.8.3

---

regression/verilog/expressions/replication1.v
src/verilog/verilog_typecheck_expr.cpp

This adds constant folding for replication operators to the Verilog typechecker.

Verilog: constant folding for replication

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h

This extracts the conversion of expressions into synthesis-time constants into a new method.

Verilog: extract `verilog_synthesist::synthesis_constant`

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h

This method can be const by replacing the `[]` operator on a map that is used by `.find(...)`.

`verilog_synthesist::current_value` can be const

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h

The left-hand side of assignments requires special-case synthesis; the symbol to be assigned must not be replaced by its value, but any array indices must be.

Verilog: separate synthesis for LHS expressions

---

src/verilog/parser.y

This changes the `non_port_module_item` grammar rule to match IEEE 1800-2017 Sec 23.2.4.

Verilog: non_port_module_item grammar rule

---

src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h

This flips the assignments generated by synthesis for module output ports to read
`c := port`
for a connected signal `c`, instead of `port := c`.

Verilog: fix assignment for module output ports

---

src/verilog/parser.y
src/verilog/verilog_expr.h
src/verilog/verilog_language.cpp
src/verilog/verilog_parse_tree.cpp
src/verilog/verilog_parse_tree.h
src/verilog/verilog_typecheck.cpp

SystemVerilog allows a broad range of items to appear at the compilation unit level.  This changes the parse tree to be a list of generic compilation unit items.

Verilog: parse tree now is a list of generic compilation unit items

---

regression/verilog/synthesis/continuous_assignment_to_variable_systemverilog2.desc
regression/verilog/synthesis/continuous_assignment_to_variable_systemverilog2.sv
src/verilog/verilog_synthesis.cpp

SystemVerilog allows continous assignments to variables.
This test exposes that inconsistent constraints get generated for this case.
This replicates issue #635.

Verilog: fix for continuous assignments to state variables

---

src/ebmc/bdd_engine.cpp
src/ebmc/bdd_engine.h
src/ebmc/k_induction.cpp
src/ebmc/k_induction.h
src/ebmc/property_checker.cpp
src/ebmc/property_checker.h

This introduces a type for the result from an engine, as a replacement for `int`.

introduce `property_checker_resultt`

---

regression/ebmc/k-induction/k-induction5.k-3.desc

The test should have been marked as CORE when merging the bugfix.

Mark k-induction test as CORE

---

regression/verilog/expressions/signed2.desc
regression/verilog/expressions/signed2.sv

The signed base 2 literal should be sign-extended.

Verilog: KNOWNBUG test for signed base 2 literal

---

regression/verilog/modules/wire_and_wire.desc
src/verilog/verilog_elaborate.cpp

Redeclarations of wires (nets) is prohibited; this adds an error message.

Verilog: error on wire redeclaration

---

regression/verilog/SVA/nexttime1.desc
src/temporal-logic/normalize_property.cpp
src/temporal-logic/normalize_property.h
src/verilog/sva_expr.h

This implement indexed `nexttime` by rewriting `nexttime[i] φ` to `always[i:i] φ`.

SVA: implement indexed nexttime

---

regression/ebmc/random-traces/bv1.desc
regression/ebmc/random-traces/initial_state1.desc
regression/ebmc/random-traces/long_trace1.desc
regression/verilog/expressions/constants1.desc
regression/verilog/expressions/equality1.desc
regression/verilog/expressions/equality2.desc
regression/verilog/expressions/static_cast1.desc
regression/verilog/structs/structs4.desc
src/verilog/expr2verilog.cpp

The conversion of constants to Verilog source now includes the signedness and width when outputting hex or binary literals.

Verilog: constant output now includes signedness and width

---

regression/verilog/expressions/size_cast1.sv
src/verilog/verilog_typecheck_expr.cpp

This allows applying size-casts to Boolean operands.

Verilog: size-cast expression with Boolean operand

---

regression/verilog/SVA/immediate3.desc
regression/verilog/SVA/static_final1.desc
regression/verilog/expressions/concatenation3.desc
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h

This changes the precedence of concatenation and replication when generating Verilog from expressions such that no additional parentheses are generated.

Verilog: `{}` and `{{}}` do not need parentheses

---

regression/verilog/expressions/equality1.desc
regression/verilog/expressions/equality2.desc
regression/verilog/expressions/signed2.desc
regression/verilog/expressions/signed2.sv
src/verilog/verilog_typecheck_expr.cpp

Verilog allows constants to be marked as signed (e.g., 'sb1).  When using base 2, 8 and 16, these need to be sign extended to 32 bits unless the number of bits is given.

Verilog: fix for signed constants

---

regression/verilog/SVA/sva_until1.desc
regression/verilog/SVA/sva_until1.sv
src/trans-word-level/property.cpp

This tightens the test performed for properties supported by the word-level BMC engine, to avoid incorrect results when given an unsupported property.

tighten test for supported word-level BMC properties

---

src/temporal-logic/temporal_logic.cpp
src/temporal-logic/temporal_logic.h

This introduces two helper functions, is_SVA_operator` and `is_SVA`, to identify expressions that are System Verilog Assertions.

introduce is_SVA_operator and is_SVA

---

regression/verilog/SVA/sequence5.desc
regression/verilog/SVA/sequence5.sv

"true" is defined as "nonzero known value" (1800-2017 12.4), and hence, neither `z` nor `x` should be 'true'.

KNOWNBUG test for casting z/x to Boolean

---

src/temporal-logic/normalize_property.cpp
src/temporal-logic/normalize_property.h

This adds two rules to the property normalizer for the negation of SVA s_eventually and SVA always.

Simplify ¬ sva_s_eventually φ --> sva_always ¬φ

---

regression/ebmc/example1/example1.sv
regression/verilog/SVA/immediate3.desc
regression/verilog/SVA/immediate3.sv
regression/verilog/SVA/static_final1.desc
regression/verilog/SVA/static_final1.sv
regression/verilog/expressions/concatenation1.v
regression/verilog/expressions/equality1.desc
regression/verilog/expressions/equality2.desc
regression/verilog/expressions/replication1.v
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

Relations are special-cased in 1800-2017 11.8.2.
If both operands are signed, both are sign-extended to the max width.
Otherwise, both are zero-extended to the max width.  In particular, signed operands are then **not** sign extended, which a typecast would do.

Verilog: typechecking for relations

---

regression/ebmc/netlist/netlist-conversion1.desc
regression/ebmc/netlist/netlist-conversion1.v
src/trans-netlist/trans_to_netlist.cpp

This fixes the case where the netlist conversion fails when there is an operand with natural or integer type.
Fixes #674.

fix for netlist conversion

---

regression/verilog/expressions/bit-extract6.desc
regression/verilog/synthesis/always_comb2.desc
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h

This repairs the output of the Verilog (not: SVA) implication operator, to read `->`, and not `|->`.

Verilog: fix for output of `->`

---

regression/verilog/SVA/eventually1.desc
regression/verilog/SVA/sva_and1.desc
regression/verilog/SVA/sva_iff1.desc
regression/verilog/SVA/sva_implies1.desc
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h

This changes the methods for the individual expressions in `expr2verilogt` to return `resultt`.

Verilog: use `resultt` for methods in `expr2verilogt`

---

regression/verilog/system-functions/past1.aig.desc
regression/verilog/system-functions/past1.bdd.desc
regression/verilog/system-functions/past2.desc
src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_properties.h
src/trans-netlist/unwind_netlist.cpp

The AIG-based backends currently do not support `$past` -- this improves the error message.

better error reporting when $past is unsupported

---

src/trans-word-level/obligations.h
src/trans-word-level/property.cpp

This introduces a class with helper methods as a wrapper for the map from counterexample length to verification conditions.

introduce `obligationst`

---

regression/verilog/expressions/power2.desc
regression/verilog/expressions/power2.sv
src/verilog/verilog_synthesis.cpp

The Verilog synthesis now lowers power expressions with constant rhs to the equivalent multiplication.

Verilog: synthesis for power expressions with constant rhs

---

regression/verilog/modules/inout_and_reg.desc
regression/verilog/modules/input_and_reg.desc
regression/verilog/modules/wire_and_reg.desc
src/verilog/verilog_elaborate.cpp

This errors redeclarations of variables, unless the original symbol is an output.

Verilog: error redeclaration of variable

---

src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_typecheck_type.cpp

This extracts the logic for typechecking packed array types into a separate method.

extract verilog_typecheck_exprt::convert_packed_array_type

---

src/verilog/Makefile
src/verilog/verilog_elaborate.cpp
src/verilog/verilog_elaborate_type.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This renames the method that elaborates types, given that it follows the elaboration procedure in the Verilog standard.

Verilog: rename convert_type method to elaborate_type

---

regression/ebmc/smv/smv_ctlspec_F1.desc
regression/ebmc/smv/smv_ctlspec_F1.smv
regression/ebmc/smv/smv_ctlspec_G1.desc
regression/ebmc/smv/smv_ctlspec_G1.smv
src/temporal-logic/temporal_logic.cpp
src/temporal-logic/temporal_logic.h
src/trans-word-level/property.cpp

This extends the fragment of CTL that is accepted by the BMC engine.

BMC: extend CTL fragment

---

regression/ebmc/smv/smv_ltlspec_R1.desc
regression/ebmc/smv/smv_ltlspec_U1.desc
src/smvlang/parser.y
src/smvlang/scanner.l

This adds scanner/parser rules for LTL U/R expressions.

SMV: parse LTL U and R

---

regression/ebmc/smv/smv_ctlspec1.desc
regression/ebmc/smv/smv_ctlspec1.smv
regression/ebmc/smv/smv_ltlspec5.desc
regression/ebmc/smv/smv_ltlspec5.smv
src/smvlang/smv_typecheck.cpp

The SMV typechecker now rejects CTL when checking LTLSPEC, and LTL when checking CTLSPEC.

SMV: reject CTL in LTLSPEC, and LTL in CTLSPEC

---

regression/ebmc/smv/smv_iff2.desc
src/smvlang/expr2smv.cpp
src/smvlang/parser.y

This replaces the use of `unsigned` and assorted integer literals for the expression precedence by an enum type.

expr2smv: enum for precedence

---

src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h
src/ebmc/k_induction.cpp
src/ebmc/neural_liveness.cpp
src/ebmc/property_checker.cpp
src/ebmc/property_checker.h
src/ebmc/ranking_function.cpp
src/ebmc/report_results.cpp
src/ebmc/report_results.h
src/ic3/m1ain.cc

The return value of the property checker now includes the property status. This is to replace status reporting as a side effect.

ebmc: `property_checker_resultt` now includes property status

---

.github/workflows/pull-request-checks.yaml
regression/verilog/case/nested_case1.desc
regression/verilog/case/nested_case1.v
regression/vlindex/Makefile
regression/vlindex/hierarchy1/hierarchy1.desc
regression/vlindex/hierarchy1/hierarchy1.v
regression/vlindex/modules1/modules1.desc
regression/vlindex/modules1/modules1.v
src/Makefile
src/verilog/verilog_preprocessor.cpp
src/vlindex/Makefile
src/vlindex/verilog_indexer.cpp
src/vlindex/verilog_indexer.h
src/vlindex/vlindex_main.cpp
src/vlindex/vlindex_parse_options.cpp
src/vlindex/vlindex_parse_options.h

This adds a recusive decent parser for quicky indexing large quantities of Verilog, tolerating parsing errors, for the purpose of creating overview data very quickly.  A new executable, `vlindex`, is added to output it.

Verilog: introduce the Verilog indexer

---

src/verilog/verilog_elaborate_type.cpp
src/verilog/verilog_interfaces.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

The `convert_range` method now returns the range, as opposed to assigning to two reference parameters.

Verilog: `convert_range` now returns range

---

regression/verilog/arrays/packed_real1.desc
regression/verilog/arrays/packed_typedef1.desc
src/verilog/verilog_elaborate_type.cpp

This adds an error message when given `real` as element type of a packed array.

SystemVerilog: packed arrays must not use real element type

---

regression/ebmc/smv/smv_ltlspec6.desc
regression/ebmc/smv/smv_ltlspec6.smv
regression/ebmc/smv/smv_ltlspec_F1.desc
regression/ebmc/smv/smv_ltlspec_F2.desc
regression/ebmc/smv/smv_ltlspec_G1.desc
regression/ebmc/smv/smv_ltlspec_G2.desc
regression/ebmc/smv/smv_ltlspec_R1.desc
regression/ebmc/smv/smv_ltlspec_U1.desc
regression/verilog/SVA/sva_until1.desc
src/temporal-logic/normalize_property.cpp
src/trans-word-level/property.cpp

Full LTL is supported by the word-level BMC engine.

BMC: support full LTL

---

regression/verilog/expressions/negation1.desc
src/verilog/aval_bval_encoding.cpp
src/verilog/aval_bval_encoding.h
src/verilog/verilog_synthesis.cpp

This adds the aval/bval encoding for Verilog negation.

Verilog: aval/bval encoding for `!`

---

regression/vlindex/hierarchy1/hierarchy1.desc
src/vlindex/verilog_indexer.cpp

Without a scope and symbol table, parsing SystemVerilog requires three tokens lookahead to distinguish module instances from variable declarations.
This replaces the two tokens used for lookahead by a `std::deque`, enabling unbounded lookahead.

vlindex: unbounded lookahead

---

regression/ebmc/random-traces/boolean1.desc
regression/ebmc/random-traces/bv1.desc
regression/ebmc/random-traces/counter_with_initial_value.desc
regression/ebmc/random-traces/long_trace1.desc
regression/ebmc/random-traces/long_trace1.random-waveform.desc
regression/ebmc/random-traces/with_submodule.desc
regression/ebmc/smv/smv3.desc

This enables various tests that use the range type to work with Z3.

bump CBMC dependency

---

regression/ebmc/smv/smv_ltlspec_R1.desc
regression/ebmc/smv/smv_ltlspec_R2.desc
regression/ebmc/smv/smv_ltlspec_R3.desc
regression/ebmc/smv/smv_ltlspec_R4.desc
src/trans-word-level/property.cpp

The expansion needs to use `true` to replace `X(p R q)` when reaching the end of the BMC unwinding.

BMC: fix encoding of `p R q`

---

regression/verilog/synthesis/continuous_assignment_to_variable_systemverilog3.desc
src/verilog/verilog_synthesis.cpp

This fixes the case when there are multiple continuous assignments to the same variable in the Verilog synthesis code.

Verilog: fix continuous assignments to variables

---

src/ebmc/k_induction.cpp
src/ebmc/random_traces.cpp
src/ebmc/ranking_function.cpp
src/trans-word-level/counterexample_word_level.cpp
src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/instantiate_word_level.h
src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp
src/trans-word-level/sequence.h
src/trans-word-level/unwind.cpp

The solver and namespace objects are not used, and hence do not need to be given as parameters.

word-level BMC: remove parameters for solver + ns

---

regression/verilog/unions/unions4.desc
regression/verilog/unions/unions4.sv
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This adds conversions from/to packed unions to/from vector types.

SystemVerilog: conversion from/to packed union

---

examples/Benchmarks/check_ranking

Assertions now go into the scope without "property." prefix.

fix property ID in the ranking benchmarks

---

src/temporal-logic/Makefile
src/temporal-logic/nnf.cpp
src/temporal-logic/nnf.h
src/trans-word-level/property.cpp

The computation of per-node NNF done in the word-level BMC encoding is independent of the engine used, and should hence live in temporal-logic/

extract per-node NNF computation for temporal logic from word-level BMC

---

regression/verilog/generate/generate-for3.desc
regression/verilog/generate/generate-for3.v
src/verilog/verilog_elaborate.cpp

The use of `generate` ... `endgenerate` became optional with 1364-2005.
Fixes issue #747.

Verilog: generate ... endgenerate is optional

---

regression/verilog/nets/implicit1.desc
regression/verilog/nets/implicit1.sv
regression/verilog/nets/implicit2.desc
regression/verilog/nets/implicit2.sv
regression/verilog/nets/implicit3.desc
regression/verilog/nets/implicit3.sv
regression/verilog/nets/implicit4.desc
regression/verilog/nets/implicit4.sv
regression/verilog/nets/implicit5.desc
regression/verilog/nets/implicit5.sv

SystemVerilog allows nets to be declared implicitly (1800 2017 Sec 6.10).

Verilog: add tests for implicit nets

---

regression/verilog/enums/enum5.desc
regression/verilog/enums/enum5.sv
src/verilog/verilog_elaborate.cpp
src/verilog/verilog_typecheck.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

Module parameters, local parameters and enums must be elaboration time constants.  This adds an error when they are not.

Verilog: reject non-constant parameters

---

src/verilog/verilog_synthesis.cpp

`verilog_synthesist::synth_expr` is always applied recursively to the operands of the given expression.  This commit pulls this out of the case split.

Verilog: pull out recursive application of verilog_synthesist::synth_expr

---

src/verilog/verilog_expr.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_synthesis.cpp

This moves the lowering for Verilog's part select expressions into an explicit `.lower()` method.

Verilog: extract `.lower()` method for part select expressions

---

regression/verilog/SVA/sequence_first_match1.desc
regression/verilog/SVA/sequence_intersect1.desc
regression/verilog/SVA/sequence_repetition1.desc
regression/verilog/SVA/sequence_repetition2.desc
regression/verilog/SVA/sequence_repetition2.sv
regression/verilog/SVA/sequence_throughout1.desc
regression/verilog/SVA/sequence_within1.desc
src/temporal-logic/temporal_logic.cpp
src/trans-word-level/property.cpp
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/verilog_typecheck_expr.cpp

This adds front-end support for eight SVA sequence operators.

SVA: add eight sequence operators to Verilog Frontend

---

regression/verilog/nets/implicit1.desc
regression/verilog/nets/implicit2.desc
regression/verilog/nets/implicit3.desc
regression/verilog/nets/implicit5.desc
regression/verilog/nets/implicit6.desc
regression/verilog/nets/implicit6.sv
regression/verilog/nets/implicit7.desc
regression/verilog/nets/implicit7.sv
src/ebmc/ebmc_parse_options.h
src/ebmc/transition_system.cpp
src/verilog/verilog_language.cpp
src/verilog/verilog_language.h
src/verilog/verilog_parameterize_module.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

1800 2017 6.10 allows implicit declarations of nets.  The type of these nets is to be derived from the LHS of the assignment or the type of the port connection.

Verilog: set type of implicit nets

---

regression/verilog/constraints/constraint1.desc
regression/verilog/constraints/constraint1.sv
src/verilog/parser.y
src/verilog/scanner.l

This adds the 1800-2017 rules for distribution weights.

SystemVerilog: grammar for distribution weights

---

regression/verilog/SVA/sequence_first_match1.sv
src/verilog/parser.y

This adds the grammar rules for the `first_match` operator with sequence match items.  The operator is still unsupported.

SVA: add grammar for `first_match` with `sequence_match_item`

---

src/temporal-logic/Makefile
src/temporal-logic/normalize_property.cpp
src/temporal-logic/normalize_property.h
src/temporal-logic/trivial_sva.cpp
src/temporal-logic/trivial_sva.h

Some of the SVA operators are not temporal operators, but state predicates only.  This moves the rewrites for these operators into a separate file.

SVA: move rewrites for state-formula SVA into separate file

---

regression/ebmc/liveness-to-safety/failing1.bdd.desc
regression/ebmc/liveness-to-safety/failing1.ic3.desc
regression/ebmc/liveness-to-safety/failing2.ic3.desc
regression/ebmc/liveness-to-safety/passing1.bdd.desc
regression/ebmc/liveness-to-safety/passing1.ic3.desc
regression/ebmc/liveness-to-safety/passing2.ic3.desc
src/ebmc/bdd_engine.cpp
src/ebmc/cegar/bmc_cegar.cpp
src/ebmc/ebmc_base.cpp
src/ebmc/ebmc_parse_options.cpp
src/ebmc/property_checker.cpp
src/ic3/m1ain.cc
src/trans-netlist/trans_to_netlist.cpp
src/trans-netlist/trans_to_netlist.h

This adds support for the combination of IC3 or BDDs and the liveness-to-safety translation.

liveness-to-safety for IC3 and BDDs

---

regression/verilog/SVA/system_verilog_assertion4.sv
src/verilog/parser.y

According to 1800 2017, both `|->` and `|=>` expect a sequence expression on the left hand side, as opposed to a property expression.

SVA: fix grammar for overlapped and nonoverlapped implications

---

regression/verilog/expressions/part-select-constant1.desc
regression/verilog/expressions/part-select-constant1.sv
src/verilog/verilog_typecheck_expr.cpp

This implements constant folding for Verilog's nonindexed part select.
Fixes #751.

Verilog: constant folding for nonindexed part select

---

regression/verilog/SVA/sva_iff2.sv
regression/verilog/SVA/sva_implies2.desc
regression/verilog/SVA/sva_implies2.sv
src/temporal-logic/normalize_property.cpp
src/trans-word-level/property.cpp

This changes the word-level BMC encoding for Fφ properties to remove counterexample traces that exhibit the following:
1) a ¬φ loop,
2) followed by one or more φ states.
While these traces demonstrate that a counterexample exists (constructed by simply expanding the ¬φ loop), they are not themselves counterexamples to Fφ.

change Fφ BMC encoding

---

regression/verilog/SVA/sva_iff2.sv
regression/verilog/SVA/sva_implies2.sv
src/temporal-logic/nnf.cpp
src/verilog/sva_expr.h

This uses SVA's until_with and s_until_with when negating SVA's until and
s_until instead of LTL's strong and weak release operators.  This way, the
resulting formula remains an SVA formula, as opposed to becoming a mixture
of SVA and LTL.

SVA: remain within SVA when negating

---

regression/verilog/SVA/issue669.desc
regression/verilog/SVA/issue669.sv
regression/verilog/SVA/sva_iff2.sv
regression/verilog/SVA/sva_implies2.sv
src/temporal-logic/nnf.cpp
src/verilog/sva_expr.h

This enables the test to parse.
Closes #669.

Update issue669.sv to use 'implies'

---

regression/verilog/system-functions/typename1.desc
regression/verilog/system-functions/typename1.sv
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This implements SystemVerilog's `$typename` system function.

Verilog: `$typename`

---

regression/verilog/SVA/sequence_repetition1.desc
regression/verilog/SVA/sequence_repetition3.desc
regression/verilog/SVA/sequence_repetition3.sv
src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/parser.y
src/verilog/sva_expr.cpp
src/verilog/sva_expr.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This implements SVA's `[*n]` sequence operator.

SVA: consecutive repetition

---

regression/verilog/nets/implicit2.sv
regression/verilog/nets/implicit6.sv
regression/verilog/nets/implicit7.sv
src/verilog/verilog_typecheck.cpp

The type of the implicit net created for a port connection is _not_ the type of the port, but an "implicit scalar net of default net type".

Verilog: fix for implicit nets for port connections

---

regression/verilog/synthesis/continuous_assignment1.desc
regression/verilog/synthesis/continuous_assignment1.sv
regression/verilog/synthesis/continuous_assignment2.desc
regression/verilog/synthesis/continuous_assignment2.sv
regression/verilog/synthesis/continuous_assignment3.desc
regression/verilog/synthesis/continuous_assignment3.sv
src/verilog/verilog_synthesis.cpp

The LHS expression of continuous assignments needs to be synthesized.

Verilog: fix for synthesis of continuous assignments

---

.github/workflows/pull-request-checks.yaml
examples/Hazard3/Hazard3.sh
regression/verilog/system-functions/past3.desc
regression/verilog/system-functions/past3.sv

The Hazard3 RISC-V CPU comes with SVA assertions.  This script downloads the RTL, and runs ebmc to check them.

example: Hazard3 CPU

---

regression/ebmc/CLI/property-not-found1.desc
regression/ebmc/CLI/property-not-found1.sv
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h

When giving an unknown property ID to `--property`, abort, as opposed to continuing with an empty set of properties.

ebmc: hard error when giving an unknown property ID

---

regression/verilog/SVA/sequence5.desc
regression/verilog/SVA/sva_and1.desc
regression/verilog/SVA/sva_iff1.desc
regression/verilog/SVA/sva_implies1.desc
src/verilog/aval_bval_encoding.cpp
src/verilog/aval_bval_encoding.h
src/verilog/verilog_synthesis.cpp

This implements casing four-valued ava/bval encoded cast to Bool.  In particular, values containing `x` or `z` cast to false, not true.

Verilog: aval/bval lowering for casts to Bool

---

src/verilog/parser.y
src/verilog/verilog_language.cpp
src/verilog/verilog_parse_tree.cpp
src/verilog/verilog_parse_tree.h

Instead of storing the module via a side-effect, `create_module` now returns the `verilog_module_sourcet`.
This enables nested modules.

Verilog: `create_module` now returns `verilog_module_sourcet`

---

README.md

This updates the EBMC readme to focus on the what, as opposed to how it's implemented.
Furthermore, `--module` is deprecated in favor of the common `--top` command-line option.

Update EBMC's README.md

---

regression/verilog/UDPs/multiplexer1.desc
regression/verilog/UDPs/multiplexer1.sv
src/verilog/parser.y

This adds the 1800-2017 grammar for user-defined combinational primitives.

Verilog: grammar for combinational UDPs

---

src/verilog/expr2verilog.cpp

Verilog: fix string generated for indexed part select

---

regression/verilog/const/const1.sv
regression/verilog/const/const2.desc
regression/verilog/const/const2.sv

This adds tests for 1800 2017 6.20.6 `const`.

SystemVerilog: add tests for `const`

---

regression/verilog/expressions/part-select-constant1.sv
src/verilog/verilog_expr.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck_expr.cpp

This implements constant folding for indexed part select expressions, following the pattern in #766.
Fixes #784.

Verilog: constant folding for indexed part select expressions

---

regression/verilog/system-functions/low1.desc
src/verilog/verilog_typecheck_expr.cpp

zero_extend now handles genvar-typed variables.

Verilog: zero_extend now considers genvar

---

src/Makefile

This avoids the use of an absolute path for the `hw_cbmc_irep_ids.h` include, which benefits compiler caches such as ccache.

use relative path for `hw_cbmc_irep_ids.h`

---

.github/workflows/ebmc-release.yaml
.github/workflows/pull-request-checks.yaml

This allows the emcc-generated code to request additional memory from the browser, as opposed to aborting with an error message.

emcc build: `-sALLOW_MEMORY_GROWTH=1`

---

regression/ebmc/k-induction/ring_buffer.desc
regression/ebmc/k-induction/ring_buffer.sv
regression/ebmc/ring_buffer_induction/test.desc

The property that is checked can be strengthened by allowing the ring buffer to hold 16 elements, as opposed to just 15.

Strengthen ring_buffer induction test

---

CHANGELOG
regression/ebmc/assumptions/assume2.bmc-with-assumptions.desc
regression/ebmc/example4_trace/test.desc
regression/verilog/functioncall/functioncall2.desc
regression/verilog/functioncall/functioncall3.desc
regression/verilog/functioncall/functioncall4.desc
src/ebmc/bmc.cpp
src/ebmc/bmc.h
src/ebmc/ebmc_parse_options.h
src/ebmc/k_induction.cpp
src/ebmc/property_checker.cpp

This implements "iterative constraint strengthening" in the word-level BMC
engine (VMCAI 2009, Query-driven Program Testing), and makes it the default.
The previous, assumption-based method remains available with
`--bmc-with-assumptions`.
When using MiniSat, the benefit on hwmcc08 is barely measurable.  When using
Cadical, the benefit is around 10%.
MiniSat iterative   88.27s
MiniSat asumptions  88.73s
Cadical iterative  103.41s
Cadical asumptions 117.74s

BMC with iterative constraint strengthening

---

regression/verilog/system-functions/past1.aig.desc
regression/verilog/system-functions/past1.bdd.desc
regression/verilog/system-functions/past2.desc
src/verilog/expr2verilog.cpp

Function calls bind strongly, and not weakly.

Verilog: fix precedence of function calls

---

regression/verilog/system-functions/past1.aig.desc
regression/verilog/system-functions/past1.bdd.desc
regression/verilog/system-functions/past2.desc
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h

These are skipped, so need to have the precedence of the operand.

Verilog: fix precedence of typecasts

---

src/verilog/Makefile
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_typecheck_sva.cpp

This moves the code for typechecking SVA expressions into separate methods
and into a separate file.

SystemVerilog: extract typechecking for SVA

---

regression/verilog/expressions/real-index.sv
regression/verilog/system-functions/typename1.sv
src/verilog/expr2verilog.cpp
src/verilog/verilog_typecheck_expr.cpp
src/verilog/vtype.cpp
src/verilog/vtype.h

This adds conversion for real-typed literals, represented as IEEE double precision.

Verilog: conversion for real literals

---

src/verilog/Makefile
src/verilog/verilog_bits.cpp
src/verilog/verilog_bits.h
src/verilog/verilog_typecheck_base.cpp
src/verilog/verilog_typecheck_base.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_types.h

This extracts the static `get_width`(...) method into a separate function, renaming to `verilog_bits`(...).

Verilog: extract `verilog_bits`(...) function

---

regression/verilog/expressions/concatenation5.desc
regression/verilog/expressions/equality3.desc
regression/verilog/expressions/reduction2.desc
regression/verilog/expressions/reduction2.v
regression/verilog/expressions/replication3.desc
regression/verilog/expressions/replication3.v
regression/verilog/expressions/shr2.desc
regression/verilog/expressions/streaming_concatenation2.desc
regression/verilog/expressions/streaming_concatenation2.sv
regression/verilog/expressions/wildcard_equality2.desc
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

This adds checks to the typechecker to enforce that the operands have an integral type.

Verilog: add checks for operators that require integral types

---

regression/verilog/data-types/queue1.desc
regression/verilog/data-types/queue1.sv

SystemVerilog offers queues, and this adds a KNOWNBUG test to track the missing support.

SystemVerilog: KNOWNBUG test for queue

---

regression/verilog/expressions/constants2.sv
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

To avoid code duplication, use `verilog_lower`(...) during constant elaboration.

Verilog: use lowering during constant elaboration

---

regression/verilog/expressions/equality1.desc
regression/verilog/expressions/equality1.v
src/verilog/verilog_lowering.cpp

This lowers Verilog's `real`/`shortreal`/`realtime` to floatbv.

Verilog: lowering for `real`/`shortreal`/`realtime`

---

regression/verilog/expressions/equality1.desc
regression/verilog/expressions/equality1.v
regression/verilog/expressions/iff1.desc
regression/verilog/expressions/iff1.sv
src/verilog/aval_bval_encoding.cpp
src/verilog/aval_bval_encoding.h
src/verilog/verilog_expr.h
src/verilog/verilog_lowering.cpp
src/verilog/verilog_typecheck_expr.cpp

This adds a lowering for Verilog's `<->` iff expression, with four-valued semantics.

Verilog: lowering for four-valued `<->`

---

src/verilog/Makefile
src/verilog/verilog_simplifier.cpp
src/verilog/verilog_simplifier.h
src/verilog/verilog_typecheck_expr.cpp

This extracts the Verilog-specific expression simplification from the type checker into a separate function, in a separate source file.

Verilog: extract expression simplifier

---

regression/verilog/SVA/if1.desc
regression/verilog/SVA/immediate2.desc
regression/verilog/SVA/sequence5.desc
regression/verilog/case/case3.desc
regression/verilog/case/case4.desc
regression/verilog/expressions/bit-extract1.desc
regression/verilog/expressions/bit-extract2.desc
regression/verilog/expressions/concatenation3.desc
regression/verilog/expressions/equality2.desc
regression/verilog/expressions/iff1.desc
regression/verilog/expressions/implies1.desc
regression/verilog/expressions/negation1.desc
regression/verilog/expressions/signed2.desc
regression/verilog/expressions/wildcard_equality1.desc
regression/verilog/modules/ports2.desc
src/verilog/verilog_expr.h
src/verilog/verilog_lowering.cpp

This benefits the SMT2 backend, which does not implement `verilog_case_equality` and `verilog_case_inequality`.

Verilog: lowering for `verilog_case_equality`

---

.github/workflows/ebmc-release.yaml
.github/workflows/pull-request-checks.yaml

This adds Cadical to the release builds for Debian/Ubuntu and Redhat.

ebmc release flow: add Cadical

---

regression/verilog/SVA/cycle_delay_star1.desc
regression/verilog/SVA/cycle_delay_star1.sv
src/verilog/parser.y

This re-orders the rules for `sequence_expr` to match 1800-2017.

SystemVerilog: grammar for `sequence_expr`

---

regression/ebmc/Properties1/test.desc
regression/ebmc/example4_trace/test.desc
regression/ebmc/range_type/range_type2.desc
regression/ebmc/small-test1/test.desc
regression/smv/LTL/smv_ltlspec4.desc

Various tests pass, owing to the CBMC submodule update.

enable passing Z3 tests

---

regression/vlindex/cmdline/cmdline.desc
regression/vlindex/cmdline/file1.v
regression/vlindex/cmdline/file2.v
src/vlindex/verilog_indexer.cpp

The Verilog indexer can now be given file names on the command line, and indexing is restricted to those files.

vlindex: restrict index to given files

---

regression/verilog/case/riscv-alu.desc
regression/verilog/enums/enum4.desc
regression/verilog/enums/enum_cast1.desc
regression/verilog/expressions/signed1.desc
regression/verilog/expressions/size_cast1.desc
regression/verilog/expressions/size_cast1.sv
regression/verilog/expressions/static_cast1.desc
regression/verilog/expressions/static_cast1.sv
regression/verilog/system-functions/signed1.desc
regression/verilog/system-functions/signed1.v
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/verilog_expr.h
src/verilog/verilog_lowering.cpp
src/verilog/verilog_typecheck_expr.cpp

This preserves the explicit casts when typechecking SystemVerilog, which enables outputting them as part of property descriptions.
They are subsequently lowered during synthesis.

SystemVerilog: retain explicit casts

---

examples/Hazard3/Hazard3-vlindex.sh
regression/verilog/preprocessor/include3.desc
src/verilog/verilog_preprocessor.cpp

This changes the behavior when processing a Verilog preprocessor `include directive.
1.  When the argument contains a directive, a better error message is issued.  Other tools process (at least some) directives within the argument.
2.  When the argument is a file name enclosed in " quotes, the character sequence is used as is, and no string literal processing is performed.  This behavior matches what other tools implement.
Note that 1800-2017 does not specify the required behavior for either one of these scenarios.

Verilog: directives inside ``include` argument

---

src/verilog/expr2verilog.cpp

This adds formatting for the primitive gate expressions nand, nor, xor, xnor.

Verilog: pretty printing for primitive gate expressions

---

regression/verilog/primitive_gates/not1.desc
regression/verilog/primitive_gates/not1.sv
src/verilog/verilog_synthesis.cpp

For a primitive not gate with input i and output o, this now generates the constraint
i = !o
as opposed to
!i = o
While logically equivalent, the new constraint is easier to read, and enables the generation of netlists that are more compact.

Veriog: synthesis of primitive not gates

---

regression/verilog/primitive_gates/or1.desc
regression/verilog/primitive_gates/or1.sv

Verilog: KNOWNBUG for primitive gates with more than two inputs

---

CHANGELOG
regression/verilog/primitive_gates/nand1.desc
regression/verilog/primitive_gates/nand1.sv
regression/verilog/primitive_gates/nand2.desc
regression/verilog/primitive_gates/nand2.sv
regression/verilog/primitive_gates/nor1.desc
regression/verilog/primitive_gates/nor1.sv
regression/verilog/primitive_gates/nor2.desc
regression/verilog/primitive_gates/nor2.sv
regression/verilog/primitive_gates/or1.desc
regression/verilog/primitive_gates/or1.sv
src/verilog/verilog_synthesis.cpp

The Verilog binary primitive gates (or, and, etc.) can be multi-ary.  This fixes the case when there are more than two inputs.
Fixes #880.

Verilog: fix for multi-ary binary primitive gates

---

regression/verilog/primitive_gates/xnor1.desc
regression/verilog/primitive_gates/xnor1.sv
regression/verilog/primitive_gates/xnor2.desc
regression/verilog/primitive_gates/xnor2.sv
regression/verilog/primitive_gates/xnor3.desc
regression/verilog/primitive_gates/xnor3.sv
src/verilog/parser.y
src/verilog/verilog_synthesis.cpp

Our backend solver does not support xnor.
On Booleans, implement via a lowering to not(xor(...)).
On bit-vectors, use the bit-wise negation of bitxor.

Verilog: implement xnor gates

---

regression/verilog/expressions/cast_to_real1.desc
regression/verilog/expressions/cast_to_real1.sv
regression/verilog/expressions/cast_to_real2.desc
regression/verilog/expressions/cast_to_real2.sv
regression/verilog/expressions/cast_to_real3.desc
regression/verilog/expressions/cast_to_real3.sv
src/verilog/verilog_lowering.cpp

Casts to `real`/`shortreal` may need to round, hence add the rounding mode during lowering.

Verilog: add rounding mode to casts to real/shortreal

---

CHANGELOG
regression/verilog/system-functions/past-instrumentation1.desc
regression/verilog/system-functions/past-instrumentation1.sv
regression/verilog/system-functions/past-instrumentation2.desc
regression/verilog/system-functions/past-instrumentation2.sv
regression/verilog/system-functions/past-instrumentation3.desc
regression/verilog/system-functions/past-instrumentation3.sv
regression/verilog/system-functions/past2.desc
regression/verilog/system-functions/past2.sv
src/ebmc/Makefile
src/ebmc/bdd_engine.cpp
src/ebmc/instrument_past.cpp
src/ebmc/instrument_past.h
src/ebmc/netlist.cpp
src/ic3/m1ain.cc
src/trans-word-level/instantiate_word_level.cpp
src/verilog/verilog_expr.cpp
src/verilog/verilog_expr.h

This adds a property/model transformation for instrumenting SystemVerilog's `$past` via additional state variables into the model.
Fixes #686.

Instrumentation for `$past`

---

regression/ebmc/ic3/bobcount.desc
regression/ebmc/ic3/bobmiterbm1multi.1033.desc
regression/ebmc/ic3/bobmiterbm1multi.1080.desc
regression/ebmc/ic3/eijks208o.desc
regression/ebmc/ic3/non_inductive1.desc
regression/ebmc/ic3/pdtvispeterson.desc
regression/ebmc/ic3/ringp0.desc
regression/ebmc/ic3/sm98a7multi.desc
regression/ebmc/ic3/visbakery.desc
regression/ebmc/ic3/viseisenberg.desc
src/ic3/m1ain.cc

This adds `report_results` to the IC3 engine, reporting the result in the same style as the other engines.

IC3: use report_results

---

src/smvlang/parser.y

This adds descriptive strings to the tokens in the SMV grammar, for the benefit of better error messages.

SMV: add strings for tokens

---

regression/verilog/data-types/vector_types2.desc
regression/verilog/data-types/vector_types2.sv
src/verilog/verilog_typecheck_expr.cpp

This removes a cast to `integer_typet{}` when elaborating constants, to enable simplification of bit-level operators.

SystemVerilog: avoid casting to `integer_typet{}`

---

regression/verilog/data-types/signed2.desc
regression/verilog/data-types/signed2.sv
regression/verilog/system_verilog_types1/test.desc
src/verilog/parser.y
src/verilog/verilog_elaborate_type.cpp

This changes the SystemVerilog parser to include an integer atom type when using `signed`/`unsigned`.

SystemVerilog: parse integer atom types when using signing

---

regression/verilog/system-functions/typename1.desc
src/verilog/verilog_lowering.cpp
src/verilog/verilog_typecheck_expr.cpp

This delays the expansion of `$typename` to preserve it in property descriptions.

SystemVerilog: delay expansion of `$typename`

---

src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h

The code for typechecking Verilog concatenations is extracted without change.

extract `verilog_typecheck_exprt::convert_expr_concatenation`

---

regression/ebmc/ic3/not_supported3.desc
regression/ebmc/ic3/not_supported3.sv
src/ic3/m1ain.cc

This improves the error handling when giving an assumption to the IC3 engine.

IC3: better error message when given assumption

---

regression/ebmc/ic3/not_supported2.desc
regression/ebmc/ic3/not_supported2.smv
src/ic3/m1ain.cc

This improves the error handling when giving an unsupported property to the IC3 engine.

IC3: only SVA always is supported

---

regression/ebmc/ic3/bobcount.desc
regression/ebmc/ic3/bobmiterbm1multi.1033.desc
regression/ebmc/ic3/bobmiterbm1multi.1080.desc
regression/ebmc/ic3/eijks208o.desc
regression/ebmc/ic3/non_inductive1.desc
regression/ebmc/ic3/pdtvispeterson.desc
regression/ebmc/ic3/ringp0.desc
regression/ebmc/ic3/sm98a7multi.desc
regression/ebmc/ic3/unconstrained_initial.desc
regression/ebmc/ic3/visbakery.desc
regression/ebmc/ic3/viseisenberg.desc
regression/ebmc/liveness-to-safety/failing1.ic3.desc
regression/ebmc/liveness-to-safety/failing2.ic3.desc
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ic3_engine.h
src/ebmc/property_checker.cpp
src/ic3/ebmc_ic3_interface.hh
src/ic3/m1ain.cc
src/ic3/p1arameters.cc
src/ic3/r0ead_input.cc
src/ic3/r1ead_input.cc
src/ic3/r2ead_input.cc
src/ic3/r3ead_input.cc
src/ic3/r4ead_input.cc
src/ic3/r5ead_input.cc
src/ic3/r6ead_input.cc
src/ic3/r7ead_input.cc

This switches the IC3 engine to use the property_checker interface.
Consequently, the exit codes now match that of the other engines.

IC3: use property_checker interface

---

regression/smv/range-type/empty.desc
regression/smv/range-type/empty.smv
src/smvlang/smv_typecheck.cpp

The SMV type checker now errors empty integer range types.

SMV: error on empty integer range

---

regression/ebmc/ic3/not_supported3.desc
src/ic3/m1ain.cc

Fixes the build after having merged the changes from #904 (and #898).

fixup! IC3: better error message when given assumption

---

regression/verilog/system-functions/typename1.desc
src/verilog/expr2verilog.cpp
src/verilog/verilog_lowering.cpp
src/verilog/verilog_typecheck_expr.cpp

This delays the expansion of string literals to preserve these in property descriptions.

SystemVerilog: delay expansion of string literals

---

regression/ebmc/engine-heuristic/basic1.desc
regression/ebmc/engine-heuristic/basic1.sv
regression/ebmc/engine-heuristic/basic2.desc
regression/ebmc/engine-heuristic/basic2.sv
regression/ebmc/engine-heuristic/basic3.desc
regression/ebmc/engine-heuristic/basic3.sv
regression/ebmc/k-induction/k-induction-unsupported2.desc
regression/ebmc/k-induction/k-induction6.desc
regression/ebmc/k-induction/k-induction7.desc
regression/ebmc/k-induction/k-induction7.sv
src/ebmc/bdd_engine.cpp
src/ebmc/ebmc_properties.cpp
src/ebmc/ebmc_properties.h
src/ebmc/k_induction.cpp
src/ebmc/property_checker.cpp
src/ebmc/property_checker.h
src/ebmc/report_results.cpp
src/trans-word-level/property.cpp

The k-induction engine now correctly reports unsupported assumptions, and is then skipped by the engine selection heuristic.
Fixes #921.

Engine heuristic: fix for assumptions unsupported by k-induction

---

src/ebmc/bmc.cpp
src/ebmc/bmc.h
src/ebmc/k_induction.cpp
src/ebmc/property_checker.cpp

`bmc(...)` now returns `property_checker_resultt`, instead of communicating the result as a side-effect on the properties data structure.

BMC: return `property_checker_resultt`

---

src/ebmc/bdd_engine.cpp
src/ebmc/bmc.cpp
src/ebmc/cegar/bmc_cegar.cpp
src/ebmc/property_checker.cpp
src/trans-netlist/unwind_netlist.cpp
src/trans-netlist/unwind_netlist.h
src/trans-word-level/property.cpp
src/trans-word-level/property.h

The property handles/literals for the BMC time frames are now returned as return values, as opposed to being returned via a reference.
This removes the ambiguity about what should happen when there are values in those vectors prior to the call.

BMC: return property handles/literals

---

regression/verilog/synthesis/posedge_vector.desc
regression/verilog/synthesis/posedge_vector.v
src/verilog/verilog_synthesis.cpp

Edge event control operators accept vector-typed operands (1800 2017 9.4.2). Only the LSB is used.

Verilog: allow vector-typed operands to edge event control

---

regression/verilog/synthesis/posedge_real.desc
regression/verilog/synthesis/posedge_real.v
src/verilog/verilog_typecheck_expr.cpp

1800-2017 6.12.1 prohibits real operands given to edge control operators. This adds an error message for this case.

Verilog: error on real operand for edge control

---

regression/verilog/SVA/cycle_delay1.desc
regression/verilog/SVA/cycle_delay1.sv
src/verilog/verilog_typecheck_sva.cpp

Replicates third example in #931.

SVA: add test with non-constant SVA cycle delays

---

regression/verilog/preprocessor/file1.desc
regression/verilog/preprocessor/file1.v
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog.h
src/verilog/verilog_preprocessor.cpp

This adds 1800 2017 22.13 \``__FILE__` and \``__LINE__` to the Verilog preprocessor.

Verilog: ``__FILE__` and ``__LINE__`

---

src/ebmc/k_induction.cpp
src/ebmc/k_induction.h
src/ebmc/property_checker.cpp

The `k_induction(...)` function now returns `property_checker_resultt`, instead of using a side-effect on an argument passed by reference.

`k_induction(...)` now returns `property_checker_resultt`

---

regression/verilog/SVA/sequence6.desc
regression/verilog/SVA/sequence6.sv
src/verilog/parser.y

This allows the use of parentheses ( ... ) in sequences.
Raised in #931.

SVA: allow parentheses around sequences

---

regression/verilog/SVA/sequence_repetition4.desc
regression/verilog/SVA/sequence_repetition4.sv
src/verilog/parser.y
src/verilog/sva_expr.cpp

The sequence abbreviation operator can be applied to a full sequence, not just state formulas.  This adds the grammar for this case.

SVA: sequence repetition for proper sequences

---

regression/verilog/SVA/sequence_and1.desc
regression/verilog/SVA/sequence_and1.sv
regression/verilog/SVA/sequence_or1.desc
regression/verilog/SVA/sequence_or1.sv
src/verilog/parser.y

The 1800-2017 SystemVerilog grammar allows `a and b` and `a or b` to be either a sequence, or a property.  If both `a` and `b` are sequences, then `a and b` and `a or b` is a sequence as well.
This changes the grammar to allow the sequence case.

SVA sequence `and`/`or`

---

src/verilog/Makefile
src/verilog/parser.y
src/verilog/scanner.l
src/verilog/verilog_parser.cpp
src/verilog/verilog_parser.h
src/verilog/verilog_scope.cpp
src/verilog/verilog_scope.h

This extracts the scope data structure from the parser class into a separate file, as the scopes need to be preserved until all Verilog parsing is finished.

Verilog: extract scope data structure from parser

---

src/verilog/parser.y

This renames a production rule in the SystemVerilog grammar to clarify that the identifier matched by the rule does not need to be new.

Verilog: rename new_identifier -> any_identifier

---

src/verilog/parser.y
src/verilog/verilog_scope.h

SystemVerilog has numerous different kinds of scopes, and this is now tracked when creating a scope.

SystemVerilog: track the kind of scope

---

src/verilog/parser.y
src/verilog/scanner.l
src/verilog/verilog_scope.cpp
src/verilog/verilog_scope.h

This adds a scope stack to the Verilog parser, to enable entering named scopes using the `::` and member operators while parsing.

Verilog: introduce scope stack

---

src/verilog/Makefile
src/verilog/parser.y
src/verilog/scanner.l
src/verilog/verilog_scope.cpp
src/verilog/verilog_scope.h

This introduces a separate token type for package identifiers, to enable parsing with just one token lookahead.

SystemVerilog: package identifier tokens

---

CHANGELOG
regression/verilog/packages/package_typedef1.sv
src/verilog/parser.y
src/verilog/verilog_elaborate_type.cpp
src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_types.h

This adds support for using typedefs defined inside a package using the `::` package scope operator.

SystemVerilog: use typedefs from package scopes

---

src/verilog/scanner.l
src/verilog/verilog_parser.h
src/verilog/verilog_scanner.h

This introduces a new data structure for the state of the Verilog scanner, as opposed to using the data structure for the parser state.

SystemVerilog: separate scanner and parser state

---

regression/verilog/packages/package2.sv
regression/verilog/packages/package_typedef1.sv
src/verilog/verilog_elaborate_type.cpp
src/verilog/verilog_expr.cpp
src/verilog/verilog_expr.h
src/verilog/verilog_typecheck_expr.cpp
src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_types.cpp
src/verilog/verilog_types.h

Dependencies on a package via the package scope operator `::` are now discovered when used in types or expressions.

SystemVerilog: discover package dependencies in expressions and types

---

regression/verilog/SVA/default_disable1.desc
regression/verilog/SVA/default_disable1.sv

The parser rules are incomplete, this causes a crash.
Replicates #974.

SVA: KNOWNBUG test for `default disable iff`

---

src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h

The precedence is now returned via `resultt`; no need to pass it as a reference.

cleanup expr2verilog

---

src/smvlang/parser.y
src/smvlang/smv_parse_tree.cpp
src/smvlang/smv_parse_tree.h
src/smvlang/smv_typecheck.cpp

This adds distinct parse tree nodes for ASSIGN init and ASSIGN next.

SMV: parser cleanup

---

regression/smv/assign/assign1.desc
regression/smv/assign/assign1.smv
regression/smv/assign/assign2.desc
regression/smv/assign/assign2.smv
regression/smv/define/define2.desc
regression/smv/define/define2.smv
regression/smv/define/define3.desc
regression/smv/define/define3.smv
regression/smv/define/define4.desc
regression/smv/define/define4.smv
regression/smv/define/define5.desc
regression/smv/define/define5.smv
regression/smv/define/define6.desc
regression/smv/define/define6.smv
src/smvlang/parser.y

`VAR x : ...` followed by `DEFINE x := ...` must be errored.

SMV: do not allow defining identifiers that are already declared

---

src/smvlang/smv_typecheck.cpp

The expression is no longer in use.

remove dead code in SMV typechecker

---

regression/smv/enums/enum3.desc
src/smvlang/smv_typecheck.cpp

This adds a check that SMV enum literals are in the target type.

SMV: type check SMV enum literals

---

src/ebmc/transition_system.cpp
src/verilog/verilog_language.cpp
src/verilog/verilog_language.h
src/verilog/verilog_preprocessor.cpp
src/verilog/verilog_preprocessor.h
src/vlindex/verilog_indexer.cpp

This removes the dependency on the global object in `util/config.h` by passing the include paths as part of the `optionst` object.

Verilog: remove dependency on `util/config.h`

---

regression/smv/range-type/range_is_enum1.desc
regression/smv/range-type/range_is_enum1.smv

The range types `x..y` are syntactic sugar for the explicit enumeration `{x, ..., y}`.

SMV: range types are enum types

---

src/smvlang/smv_typecheck.cpp

The validity check for SMV range types is split from the conversion.

SMV: split type checking and type conversion

---

src/smvlang/parser.y
src/smvlang/smv_parse_tree.h

References are changed to rvalue references to avoid some copying when populating the parse tree.

SMV: avoid some expression copies

---

regression/verilog/expressions/cast_from_real1.desc
regression/verilog/expressions/cast_from_real1.sv
regression/verilog/expressions/cast_to_real1.sv
regression/verilog/expressions/cast_to_real2.desc
src/verilog/verilog_lowering.cpp

Casts from `real`/`shortreal`/`realtime` to integers must use round-to-nearest-ties-to-away.
The standard doesn't specify how to round int-to-float or double-to-single. We use RNA for consistency.

SystemVerilog: floating-point casts

---

regression/smv/expressions/smv_if2.desc
regression/smv/expressions/smv_if2.smv
regression/smv/range-type/range_type5.desc
src/smvlang/smv_parse_tree.h
src/smvlang/smv_typecheck.cpp

Given `ASSIGN lhs := rhs`, require `rhs` to have a type no larger than the type of `lhs`.
This enables better error messages.

SMV: make `ASSIGN` typed

---

CHANGELOG
regression/smv/LTL/smv_ltlspec_V1.desc
regression/smv/LTL/smv_ltlspec_V1.smv
regression/smv/LTL/smv_ltlspec_V2.desc
regression/smv/LTL/smv_ltlspec_V2.smv
regression/smv/LTL/smv_ltlspec_V3.desc
regression/smv/LTL/smv_ltlspec_V3.smv
regression/smv/LTL/smv_ltlspec_V4.desc
regression/smv/LTL/smv_ltlspec_V4.smv
src/smvlang/expr2smv.cpp
src/smvlang/parser.y

NuSMV's LTL release operator is `V`, not `R`.

SMV: the LTL release operator is "V"

---

.github/workflows/pull-request-checks.yaml

Github will remove the Ubuntu 20.04 LTS runner on 2025-04-01.  This moves the existing jobs from 20.04 to 24.04.

CI: Ubuntu 20.04 -> 24.04

---

CHANGELOG
regression/verilog/expressions/integer_literals1.desc
regression/verilog/expressions/integer_literals1.sv
src/verilog/convert_literals.cpp
src/verilog/scanner.l
src/verilog/verilog_typecheck_expr.cpp

This adds the SystemVerilog unbased unsized literals.

SystemVerilog: unbased unsized literals

---

CHANGELOG
regression/verilog/expressions/integer_literals1.sv
src/verilog/convert_literals.cpp
src/verilog/scanner.l
src/verilog/verilog_typecheck_expr.cpp

This adds Verilog's 'dx, 'dX, 'dz, 'dZ, with optional size and signedness.

Verilog: 'dx, 'dz

---

regression/verilog/SVA/initial1.desc
src/temporal-logic/temporal_logic.cpp

This adds SVA's `s_always` to the list of temporal logic operators.

Bugfix: `s_always` is a temporal logic operator

---

regression/verilog/primitive_gates/xnor1.desc
src/verilog/expr2verilog.cpp

There is no need to add parentheses around function application expressions.

Verilog: precedence of function application expressions

---

src/temporal-logic/normalize_property.cpp
src/trans-word-level/sequence.cpp
src/verilog/sva_expr.h

The indices and bounds of `nexttime`, `s_nexttime`, `s_always`, and `eventually` are constants after elaboration.  This strengthens the types of these bounds to `constant_exprt`.

SVA: typing for constant bounds of ranged/indexed operators

---

regression/verilog/SVA/initial1.desc
regression/verilog/SVA/initial1.sv
src/ebmc/completeness_threshold.cpp
src/temporal-logic/normalize_property.cpp
src/trans-word-level/sequence.cpp
src/verilog/sva_expr.h

This extends the completeness threshold logic to cover the bounded `always` and
`s_always` operators.

ebmc: completeness threshold for SVA's `always` and `s_always`

---

src/temporal-logic/nnf.cpp
src/trans-word-level/property.cpp
src/verilog/sva_expr.h

IEEE 1800-2017 uses the terminology antecedent/consequent for the lhs/rhs of `|->`, `|=>`, `#-#`, `#=#`.  This adds methods with these names to obtain the corresponding operands.

SVA: antecedent/consequent methods

---

regression/verilog/SVA/sequence_repetition6.desc
regression/verilog/SVA/sequence_repetition6.sv
src/verilog/verilog_typecheck_sva.cpp

This adds a check to the typechecker to enforce that the SVA sequence repetition operators are given sequence arguments.

SVA: `[*]`, `[+]` and `[*x:y]` require sequence arguments

---

CHANGELOG
regression/verilog/SVA/sequence_first_match2.desc
regression/verilog/SVA/sequence_implication1.desc
regression/verilog/SVA/sequence_implication1.sv
src/temporal-logic/temporal_logic.cpp
src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp

The sequence implication operators `|->` and `|=>` are property expressions, and not sequence expressions.
Furthermore, the implication must hold for _all_ matches of the LHS sequence; a single one is not sufficient.

SVA: bugfix for sequence implication operators

---

CHANGELOG
regression/verilog/SVA/sequence_repetition2.desc
regression/verilog/SVA/sequence_repetition2.sv
src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp

This implements the SVA sequence repetition operators `x[*]` and `x[+]` when `x` is a state formula.

BMC: implement SVA `[*]` and `[+]` for state formulas

---

.github/workflows/syntax-checks.yaml

Versions of `git-clang-format` later than 11 issue exit code 1 when changes were made to the source code. Although our CI job ended with a non-zero exit code as expected, it terminated early than wanted so that the differences are not printed to the log.
See https://github.com/diffblue/hw-cbmc/actions/runs/14080967185/job/39433628824?pr=1036 for an example of such a failure.

Fix display of code changes in clang-format CI action

---

src/ic3/aux_types.hh
src/ic3/build_prob/g3en_cnf.cc
src/ic3/dnf_io.hh
src/ic3/e4xclude_state.cc
src/ic3/i1nit.cc
src/ic3/i2nit_sat_solvers.cc
src/ic3/m0ic3.hh
src/ic3/m1ain.cc
src/ic3/my_printf.cc
src/ic3/p5ick_lit.cc
src/ic3/r0ead_input.cc
src/ic3/r4ead_input.cc
src/ic3/s2horten_clause.cc
src/ic3/seq_circ/a4dd_spec_buffs.cc
src/ic3/seq_circ/ccircuit.hh

This fixes instances in the IC3 implementation where variables are only used for `assert`, leading to errors when compiling with `g++` 13.3.0.
This also removes `assert(false)` in two instances in the IC3 implementation.

Fix unused variables that only appear in `assert`

---

src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp
src/trans-word-level/sequence.h

This introduces a class `sequence_matcht`, with members named `end_time` and `condition`, to replace an `std::pair<,>` with the same data.
This also introduces the type `sequence_matchest` to denote a vector of sequence matches.

BMC: `sequence_matcht`

---

regression/verilog/SVA/if1.desc
src/verilog/verilog_typecheck_sva.cpp

SVA `if` expressions are property expressions, and hence boolean.

SVA: add type to SVA `if` expressions

---

src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_typecheck_sva.cpp

This introduces a method to check operands of SVA expressions that are required to be an SVA property.

SVA: `require_sva_property`

---

src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_typecheck_sva.cpp

This adds missing calls to `require_sva_sequence` in the SVA type checker. The method changes the type of the argument to Boolean when necessary, to match the behavior of `require_sva_property`.

SVA: `require_sva_sequence`

---

CHANGELOG
regression/verilog/SVA/sequence_and3.desc
src/trans-word-level/sequence.cpp

This fixes the case in which either the LHS or RHS (or both) of an SVA sequence `and` expression may have multiple matches.  In this case, the cross-product of the LHS/RHS matches must be considered, as opposed to the conjunction of the LHS/RHS matches.

BMC: fix encoding of SVA sequence `and`

---

src/ebmc/bdd_engine.cpp
src/temporal-logic/Makefile
src/temporal-logic/ctl.cpp
src/temporal-logic/ltl.cpp
src/temporal-logic/temporal_logic.h

The BDD engine is changed to avoid searching unsupported properties for atomic propositions.

BDD engine: only look for atomic propositions in supported properties

---

src/verilog/expr2verilog.cpp

The Visual Studio C++ compiler limits the number of `if` ...  `else` nests. This temporarily fixes the compilation error by merging four cases.

Verilog: work around VS's block nesting limit

---

src/ebmc/bdd_engine.cpp
src/temporal-logic/temporal_logic.cpp
src/temporal-logic/temporal_logic.h
src/trans-netlist/instantiate_netlist.cpp
src/trans-netlist/instantiate_netlist.h
src/trans-netlist/netlist.cpp
src/trans-netlist/netlist.h
src/trans-netlist/trans_to_netlist.cpp
src/trans-netlist/unwind_netlist.cpp
src/trans-netlist/unwind_netlist.h

The netlist data structure can store properties to check about the netlist.
This replaces the std::variant data structure for storing properties for a
few special cases of temporal logic formulas by an encoding using
expressions over `literal_exprt`.

netlists can now track properties with arbitrary shapes

---

src/smvlang/expr2smv.cpp

The conversion of SMV IR to text now skips over the typecast expressions generated by the type checker.

SMV: convert typecast expressions

---

src/temporal-logic/temporal_logic.cpp
src/temporal-logic/temporal_logic.h

Parts of SVA map directly to LTL.  This allows extending the set of formulas converted to LTL when outputting an SMV model.

SMV netlist: translate some SVA to LTL

---

regression/ebmc/smv-netlist/smv1.desc
regression/ebmc/smv-netlist/smv1.smv
regression/ebmc/smv-netlist/verilog1.desc
regression/ebmc/smv-netlist/verilog1.sv
src/ebmc/bdd_engine.cpp
src/trans-netlist/instantiate_netlist.cpp
src/trans-netlist/smv_netlist.cpp

The SMV to netlist conversion now uses expr2smv for outputting the property, which enables outputting full LTL or CTL.

smv-netlist: use expr2smv for property

---

src/temporal-logic/trivial_sva.cpp
src/trans-word-level/property.cpp
src/verilog/expr2verilog.cpp
src/verilog/sva_expr.h

This introduces `sva_sequence_property_expr_baset`, to serve as a base class for `sva_weak_exprt`, `sva_strong_exprt`, and `sva_sequence_property_exprt`.

`sva_sequence_property_expr_baset`

---

regression/smv/word/extend1.desc
regression/smv/word/extend1.smv
regression/smv/word/resize1.desc
regression/smv/word/resize1.smv
regression/smv/word/signed1.desc
regression/smv/word/signed1.smv
regression/smv/word/unsigned1.desc
regression/smv/word/unsigned1.smv
src/smvlang/expr2smv.cpp
src/smvlang/expr2smv_class.h
src/smvlang/smv_typecheck.cpp

We currently expect that our solver backends support all expressions generated by the SMV-front-end as-is.
To avoid introducing additional, redundant expressions, this adds a lowering pass to the SMV type checker.
The lowering pass lowers SMV extend expressions to typecast expressions.

SMV: add a lowering pass

---

regression/smv/LTL/smv_ltlspec_R2.desc
regression/smv/LTL/smv_ltlspec_V2.desc
src/temporal-logic/normalize_property.cpp
src/temporal-logic/normalize_property.h

This simplification enables printing shorter counterexample traces.

simplify `false R ψ` to `G ψ`

---

regression/ebmc/smv-netlist/verilog1.desc
regression/ebmc/smv-netlist/verilog1.sv
src/ebmc/bdd_engine.cpp
src/ebmc/cegar/bmc_cegar.cpp
src/ebmc/property_checker.cpp
src/trans-netlist/netlist.h
src/trans-netlist/smv_netlist.cpp
src/trans-netlist/trans_to_netlist.cpp

This includes properties that haven't been translated as `{}` empty in the map, enabling output of a comment when a property isn't translated when creating the netlist.

netlists: include properties that are not translated in map

---

regression/ebmc/smv-netlist/always_with_range1.desc
regression/ebmc/smv-netlist/always_with_range1.sv
regression/ebmc/smv-netlist/nexttime1.desc
regression/ebmc/smv-netlist/nexttime1.sv
src/temporal-logic/temporal_logic.cpp

This adds further translation cases to the SVA-to-LTL translator.

translate `s_always` and ranged `always` into LTL

---

regression/verilog/SVA/sequence4.sv

This extends an existing test with the case of a sequence concatenation delay 0.

SVA: test for sequence concatenation with 0 delay

---

regression/verilog/SVA/cover_sequence1.desc
regression/verilog/SVA/cover_sequence1.sv
src/temporal-logic/normalize_property.cpp
src/temporal-logic/normalize_property.h

This changes the implicit 'always' used for SVA cover properties from LTL G to SVA `always`.  This avoids a mixture of LTL and SVA, which is not supported by the BMC backend.

bugfix for SVA cover

---

regression/verilog/SVA/cover_sequence2.desc
regression/verilog/SVA/cover_sequence2.sv

SVA cover properties pass even when the bound is insufficient to prove them.

KNOWNBUG test for SVA cover

---

CHANGELOG
regression/verilog/SVA/sequence_within1.desc
regression/verilog/SVA/sequence_within1.sv
src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp
src/verilog/sva_expr.h
src/verilog/verilog_typecheck_sva.cpp

This implements the SVA sequence `within` operator in the word-level BMC backend.

BMC: SVA sequence `within`

---

.github/workflows/pull-request-checks.yaml

The download of GNU parallel fails frequently, and the tool is not currently used.

CI: remove download of GNU parallel

---

regression/ebmc/smv-word-level/verilog1.desc
regression/ebmc/smv-word-level/verilog1.sv
src/ebmc/output_smv_word_level.cpp

Some parts of SVA map to LTL, which can be used by the SMV word-level output.

SMV word-level output now converts SVA

---

regression/smv/range-type/range_type4.desc
regression/smv/word/bitwise1.desc
src/smvlang/expr2smv.cpp

NuSMV uses a different precedence of the not operator `!` than CMU SMV.  This commit special-cases this operator, and adds parentheses to avoid this ambiguity.

SMV: precedence of `!`

---

regression/verilog/SVA/sequence2.desc
regression/verilog/SVA/sequence2.sv
regression/verilog/SVA/sequence3.desc
regression/verilog/SVA/sequence3.sv
src/temporal-logic/normalize_property.cpp
src/temporal-logic/temporal_logic.cpp
src/trans-word-level/sequence.cpp
src/verilog/sva_expr.cpp
src/verilog/sva_expr.h
src/verilog/verilog_typecheck_sva.cpp

Rewriting SVA sequences to SVA properties only works if these sequences are at the property level.

fix SVA sequence simplifications

---

src/verilog/sva_expr.h

This changes the type of various SVA sequence expressions from `bool` to `verilog_sva_sequence`.

SVA: sequence expressions should have sequence type

---

src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/parser.y
src/verilog/sva_expr.cpp
src/verilog/sva_expr.h
src/verilog/verilog_typecheck_sva.cpp

This introduces `sva_sequence_repetition_exprt` as a base class for the SVA repetition operators `[*...]`, `[=...]`, `[->...]`.

Introduce `sva_sequence_repetition_exprt`

---

regression/ebmc/smv-netlist/s_until1.desc
regression/ebmc/smv-netlist/s_until1.sv
regression/verilog/SVA/s_until1.desc
regression/verilog/SVA/s_until1.sv
src/temporal-logic/temporal_logic.cpp

This adds conversion for the SVA operators `s_until` and `s_until_with` to LTL.

convert `s_until` and `s_until_with` to LTL

---

regression/ebmc/smv-netlist/cycle_delay1.desc
regression/ebmc/smv-netlist/cycle_delay1.sv
regression/ebmc/smv-netlist/cycle_delay2.desc
regression/ebmc/smv-netlist/cycle_delay2.sv
regression/verilog/SVA/cycle_delay2.desc
regression/verilog/SVA/cycle_delay2.sv
src/temporal-logic/temporal_logic.cpp
src/verilog/sva_expr.h

This adds support for mapping some SVA sequences to equivalent LTL.

SVA to LTL now converts SVA sequences

---

regression/verilog/SVA/cover_sequence4.desc
src/trans-word-level/sequence.cpp
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/verilog_typecheck_sva.cpp

Both the goto repetition operator and the non-consecutive repetition operator can either take a singleton number of repetition or a range.
This adds support for the range case.

SVA's `[->x:y]` and `[=x:y]`

---

regression/verilog/synthesis/rf1.desc
src/verilog/verilog_synthesis.cpp

Assignments during Verilog synthesis may be no-op (e.g., out-of-bound). This fix prevents generating an untyped auxiliary variable assignment in this case.
Fixes #1050.

fix for no-op assignments during Verilog synthesis

---

src/trans-netlist/trans_to_netlist.cpp

Instead of passing the `aig_prop_constraintt` as an argument to most methods, make it a member of class `convert_trans_to_netlistt`.

make the `aig_prop_constraintt` a member `convert_trans_to_netlistt`

---

regression/ebmc/smv-netlist/s_until1.desc
src/trans-netlist/smv_netlist.cpp

NuSMV no longer accepts `1`/`0` for `TRUE`/`FALSE`.

SMV netlists: use `TRUE`/`FALSE` instead of `1`/`0`

---

regression/verilog/SVA/s_always1.desc
regression/verilog/SVA/s_always1.sv
src/temporal-logic/nnf.cpp

This adds the missing case of `s_always` when generating NNF for SVA.

implement NNF for SVA `s_always`

---

src/smvlang/Makefile
src/smvlang/smv_expr.cpp
src/smvlang/smv_expr.h
src/smvlang/smv_typecheck.cpp

This introduces classes for the existing SMV expressions.

SMV: introduce classes for `extend`, `resize`, `signed`, `unsigned`

---

regression/verilog/SVA/sequence_repetition7.desc
regression/verilog/SVA/sequence_repetition7.sv
src/trans-word-level/sequence.cpp
src/verilog/sva_expr.cpp
src/verilog/sva_expr.h

This implements the SVA operator `op[*x:y]` for the case when op is a sequence.

SVA `[*...]` for sequence operands

---

.github/workflows/ebmc-release.yaml

Ubuntu 20.04 runners have been retired.

Bump Ubuntu version in CI release action

---

src/trans-netlist/trans_to_netlist.cpp

This adds `netlist_boolbvt` as a member to `convert_trans_to_netlistt`.  This enables the retention of the expression cache that `boolbvt` implements, and hence, sharing of common subexpressions.

add a `netlist_boolbvt` member to `convert_trans_to_netlistt`

---

regression/ebmc/smv-netlist/always_with_range1.desc
regression/ebmc/smv-netlist/cycle_delay2.desc
src/trans-netlist/trans_to_netlist.cpp

This enables sharing common subexpressions in the property, reducing the size of the netlist.

use `netlist_boolbvt` for the property

---

src/temporal-logic/sva_to_ltl.cpp

This refactors the SVA-to-LTL sequence translation to return a vector instead of an expression.  This makes it easier to implement the sequence repetition operators.

SVA-to-LTL: refactoring to use vector

---

regression/ebmc/smv-word-level/verilog1.desc
regression/ebmc/smv-word-level/verilog2.desc
regression/ebmc/smv-word-level/verilog2.sv
src/smvlang/expr2smv.cpp
src/smvlang/expr2smv_class.h

This adds conversion for a variety of typecast expressions into SMV syntax.

SMV: convert typecasts to SMV

---

src/smvlang/parser.y

This renames the nonterminals `variable_name` to `variable_identifier`, and `qstring_list` to `complex_identifier`, to match the NuSMV 2.7 manual.

SMV grammar: rename `variable_name` and `qstring_list`

---

src/temporal-logic/Makefile
src/temporal-logic/sva_sequence_match.cpp
src/temporal-logic/sva_sequence_match.h
src/temporal-logic/sva_to_ltl.cpp

This extracts the class that represents potential SVA sequence matches, and the function that generates these from SVA sequence expressions into a separate file.

extract `sva_sequence_matcht`

---

regression/ebmc/smv-word-level/verilog2.desc
src/ebmc/output_smv_word_level.cpp

This fixes the SMV word-level output for in-state invariants.

Bugfix: use `INVAR` for SMV word-level in-state invariants

---

CHANGELOG
regression/verilog/preprocessor/elsif1.desc
regression/verilog/preprocessor/elsif2.desc
regression/verilog/preprocessor/elsif2.v
src/verilog/verilog_preprocessor.cpp

This adds the `elsif preprocessor directive to the Verilog preprocessor.

Verilog: `elsif

---

regression/verilog/assignments/extension-and-truncation1.desc
regression/verilog/assignments/extension-and-truncation1.sv
regression/verilog/expressions/conversions1.desc

This tests the behavior when an assignment requires extension or truncation.

test for assignment extension and truncation

---

regression/smv/syntax-errors/syntax1.desc
regression/smv/syntax-errors/syntax3.desc
src/smvlang/parser.y
src/smvlang/scanner.l

This renames the token identifiers used for SMV identifiers to better match the NuSMV manual.

SMV: rename `STRING_Token`, `QSTRING_Token` and `QUOTE_Token`

---

src/ebmc/ebmc_parse_options.cpp
src/ebmc/show_trans.cpp
src/ebmc/show_trans.h

The `show_trans*` family of functions now
1. gets the transition system as argument, as opposed to using `ebmc_baset` to create it;
2. gets the output stream as argument, as opposed to creating it itself.

signature of show_trans* family of functions

---

regression/verilog/expressions/cast_from_real2.desc
src/verilog/verilog_typecheck_expr.cpp

This adds implicit casts from real to integer types.

Verilog: casts from real to int

---

regression/smv/CTL/smv_ctlspec2.desc
regression/smv/CTL/smv_ctlspec2.smv
regression/smv/CTL/smv_ctlspec3.desc
regression/smv/CTL/smv_ctlspec3.smv
regression/smv/LTL/smv_ltlspec7.desc
regression/smv/LTL/smv_ltlspec7.smv
src/smvlang/smv_typecheck.cpp
src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/instantiate_word_level.h
src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp

This adds a check to the SMV type checker that prohibits the use of `next(...)` inside temporal-logic properties.  This matches the behavior of NuSMV.

SMV: properties must not contain `next(...)`

---

.github/workflows/pull-request-checks.yaml

This bumps the OS X version of the MacOS runner.

CI: macos-14 -> macos-15

---

regression/ebmc-spot/sva-buechi/eventually1.desc
regression/ebmc-spot/sva-buechi/eventually2.desc
src/temporal-logic/ltl_sva_to_string.cpp
src/verilog/sva_expr.h

This adds support for SVA `eventually` to the SVA-to-Buechi translation.

SVA-to-Buechi: `eventually`

---

regression/ebmc-spot/sva-buechi/sva_until1.desc
src/temporal-logic/ltl_sva_to_string.cpp

This adds conversion for the weak until and weak+strong release operators.

SVA-to-Buechi: release/until operators

---

regression/verilog/SVA/empty_sequence1.desc
regression/verilog/SVA/sequence_repetition2.desc
regression/verilog/SVA/sequence_repetition2.sv
src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp
src/trans-word-level/sequence.h

SVA empty matches do not evaluate to true when used as property.

word-level BMC: empty sequences

---

src/temporal-logic/ltl_sva_to_string.cpp
src/temporal-logic/ltl_sva_to_string.h

This removes an unused member from `ltl_sva_to_stringt::resultt`.

remove `ltl_sva_to_stringt::resultt::e`

---

examples/Benchmarks/i2c_11.sv
examples/Benchmarks/i2c_12.sv
examples/Benchmarks/i2c_13.sv
examples/Benchmarks/i2c_14.sv
examples/Benchmarks/i2c_15.sv
examples/Benchmarks/i2c_16.sv
examples/Benchmarks/i2c_17.sv
examples/Benchmarks/i2c_18.sv
examples/Benchmarks/i2c_19.sv
examples/Benchmarks/i2c_20.sv
examples/Benchmarks/i2c_3.sv
examples/Benchmarks/i2c_4.sv
examples/Benchmarks/i2c_5.sv
examples/Benchmarks/i2c_6.sv
examples/Benchmarks/i2c_7.sv
examples/Benchmarks/i2c_8.sv
examples/Benchmarks/i2c_9.sv

This removes an already implicit SVA always operator, and a redundant eventually operator from a set of NeurIPS 2024 benchmarks.

fixup i2c_*.sv SVA

---

CHANGELOG
regression/verilog/typedef/typedef2.sv
src/verilog/parser.y

Verilog generate blocks may be named, which creates a scope.

Verilog: fix for named generate block scopes

---

src/trans-word-level/property.cpp
src/trans-word-level/sequence.cpp
src/trans-word-level/sequence.h

This adds a wrapper method that returns the condition of a potential SVA sequence match.

add `sequence_matcht::condition()`

---

regression/smv/invar/invar1.desc
regression/smv/invar/invar1.smv
regression/smv/invar/invar2.desc
regression/smv/invar/invar2.smv
src/smvlang/smv_typecheck.cpp

This errors the use of `next(...)` in `INVAR`, which matches NuSMV's behavior.

SMV: disallow `next(...)` in `INVAR`

---

CHANGELOG
regression/verilog/system-functions/onehot1.desc
regression/verilog/system-functions/onehot1.sv
src/verilog/verilog_simplifier.cpp

`$onehot` and `$onehot0` are now elaboration-time constant.

Verilog: constant folding for `$onehot` and `$onehot0`

---

src/temporal-logic/ltl_sva_to_string.cpp
src/temporal-logic/ltl_sva_to_string.h

This strengthens the typing of the parameters of the methods `prefix` and `suffix`, moving type checks to the call site.

strengthen typing in `ltl_sva_to_stringt`

---

CHANGELOG
regression/verilog/SVA/followed-by5.bmc.desc
src/trans-word-level/property.cpp

This implements the correct semantics in the word-level BMC encoding when the LHS of the followed-by operators is an empty match.

word-level BMC: fix `#-#` and `#=#` for empty matches

---

src/temporal-logic/ltl_sva_to_string.cpp
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h
src/verilog/parser.y
src/verilog/sva_expr.cpp
src/verilog/sva_expr.h
src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_typecheck_sva.cpp
unit/temporal-logic/sva_sequence_match.cpp

The SVA cycle delay operator `##[...]` can have an optional left-hand side operand.  This adds an operand to the expression, which is nil when not used.

add (optional) lhs to SVA cycle delay operator

---

regression/ebmc-spot/sva-buechi/sequence_repetition5.desc
regression/verilog/SVA/empty_sequence1.desc
regression/verilog/SVA/sequence_repetition5.desc
src/verilog/expr2verilog.cpp
src/verilog/expr2verilog_class.h

This adds parentheses around the arguments of SVA `##` to avoid ambiguity.

SVA: parentheses around the arguments of `##`

---

src/ebmc/bdd_engine.cpp
src/ebmc/output_smv_word_level.cpp
src/temporal-logic/sva_to_ltl.cpp
src/temporal-logic/sva_to_ltl.h
src/trans-netlist/instantiate_netlist.cpp
src/trans-netlist/trans_to_netlist.cpp

`SVA_to_LTL(expr)` now throws an exception when given an expression that does not map to LTL.  The exception includes a subexpression that is not convertible.

`SVA_to_LTL` now throws exception

---

regression/ebmc-spot/sva-buechi/sequence_first_match1.desc
regression/ebmc-spot/sva-buechi/sequence_first_match2.desc
regression/ebmc-spot/sva-buechi/sequence_throughout1.desc
regression/ebmc-spot/sva-buechi/sequence_within1.desc
regression/ebmc-spot/sva-buechi/unbounded1.desc
src/temporal-logic/ltl_sva_to_string.cpp
src/temporal-logic/ltl_sva_to_string.h
src/temporal-logic/ltl_to_buechi.cpp

When given an expression that cannot be converted, the operator `ltl_sva_to_stringt(expr)` now throws an error class that includes a subexpression cannot be converted.

`ltl_sva_to_stringt::operator(expr)` now throws error class

---

regression/smv/CTL/smv_ctlspec_AFAG1.bdd.desc
regression/smv/CTL/smv_ctlspec_AFAG1.bmc.desc
regression/smv/CTL/smv_ctlspec_AFAG1.smv
regression/smv/LTL/smv_ltlspec_FG1.bdd.desc
regression/smv/LTL/smv_ltlspec_FG1.bmc.desc
regression/smv/LTL/smv_ltlspec_FG1.smv

Both the BDD and BMC engines return the wrong answer for this test.

KNOWNBUG test for `FGp`

---

regression/ebmc-spot/sva-buechi/empty_sequence1.bdd.desc
regression/verilog/SVA/empty_sequence1.bdd.desc
src/temporal-logic/Makefile
src/temporal-logic/ltl_sva_to_string.cpp
src/temporal-logic/rewrite_sva_sequence.cpp
src/temporal-logic/rewrite_sva_sequence.h
src/temporal-logic/sva_sequence_match.cpp
src/temporal-logic/temporal_logic.cpp
src/trans-word-level/sequence.cpp
src/verilog/sva_expr.cpp
src/verilog/sva_expr.h

This adds a facility to rewrite SVA sequences using SVA `or` such that they do not admit empty matches.

rewrite SVA sequences

---

src/smvlang/parser.y

This aligns some white space in the Bison parser for SMV.

whitespace in the SMV parser

---

regression/smv/expressions/smv_union1.desc
regression/smv/expressions/smv_union1.smv
regression/smv/expressions/smv_union2.desc
regression/smv/expressions/smv_union2.smv

This adds two tests for SMV `union` expressions.

SMV: two tests for `union`

---

src/smvlang/parser.y

This splits up and renames the `formula_list` production rule, to match the NuSMV manual.

SMV: split up and rename `formula_list`

---

src/smvlang/parser.y

This reorders the rules for SMV terms to match the ordering in the NuSMV 2.7 manual.

SMV grammar: reorder rules to match NuSMV manual

---

regression/verilog/SVA/sequence_not1.desc
regression/verilog/SVA/sequence_not1.sv
src/verilog/verilog_typecheck_sva.cpp

The SVA `not`/`implies`/`iff` operators yield a property, even when applied to a sequence, and hence, use as a sequence should be errored.

SVA: `not`/`implies`/`iff` operators yield a property

---

regression/smv/next/next1.desc
regression/smv/next/next1.smv
regression/smv/next/next2.desc
regression/smv/next/next2.smv
regression/smv/next/next3.desc
regression/smv/next/next3.smv

This adds three tests for SMV `next` expressions.

SMV: tests for `next(...)`

---

regression/ebmc-spot/sva-buechi/sequence2.desc
regression/ebmc-spot/sva-buechi/strong1.desc
src/ebmc/instrument_buechi.cpp
src/temporal-logic/temporal_logic.cpp

The Buechi flow now marks properties that cannot be converted into a Buechi acceptance condition as unsupported.

Buechi: mark unconverted properties as unsupported

---

unit/Makefile
unit/temporal-logic/trivial_sva.cpp

This adds unit tests for the `trivial_sva(expr)` simplification.

Unit tests for `trivial_sva(...)`

---

src/temporal-logic/trivial_sva.cpp
unit/temporal-logic/trivial_sva.cpp

The rewrites in `trivial_sva` that depend on the operands must be done post-traversal, not pre-traversal.

fix `trivial_sva(...)`

---

src/smvlang/smv_typecheck.cpp

The SMV scanner generates separate tokens for the `TRUE`/`FALSE` keywords; hence, there is no need to recognise these as special identifiers in the type checker.

SMV: `TRUE`/`FALSE` are keywords

---

src/smvlang/parser.y

NuSMV allows a subset of the expression syntax to be used as variable identifiers.  This changes the SMV grammar to use expressions to store the result of the `complex_identifier` rule.

SMV: complex identifiers are now parsed as expressions

---

src/smvlang/parser.y

1.  The production rule for module parameters is renamed from `module_argument_list` to `module_parameters`, to match the NuSMV manual.
2.  A module parameter now needs to be an `identifier`, as opposed to a `variable_identifier`, to match what NuSMV does.

SMV: grammar for module parameters

---

regression/smv/LTL/smv_ltlspec_or1.desc
regression/smv/LTL/smv_ltlspec_or1.smv

This adds a test for an LTL property with a top-level 'or'.

SMV: test for LTL property with 'or'

---

src/ebmc/bmc.cpp
src/ebmc/ebmc_properties.h
src/ebmc/liveness_to_safety.cpp
src/trans-word-level/lasso.cpp
src/trans-word-level/lasso.h
src/trans-word-level/property.cpp
src/trans-word-level/property.h

Instead of examining the property, the BMC engine now looks for the use of a lasso symbol in the property encoding.
This prevents a mismatch between the two methods.

BMC now checks for use of lasso symbol

---

src/ebmc/liveness_to_safety.cpp

The liveness-to-safety translation now exists early if there is no property it supports.

liveness-to-safety: exit if there is no supported property

---

src/smvlang/parser.y
src/smvlang/smv_parse_tree.cpp
src/smvlang/smv_parse_tree.h
src/smvlang/smv_typecheck.cpp

Instead of using a separate data structure, variable definitions are now items in the parse tree like all other syntactic elements.

SMV: variable definitions are now parse tree items

---

src/trans-word-level/instantiate_word_level.cpp
src/trans-word-level/instantiate_word_level.h
src/trans-word-level/property.cpp
src/trans-word-level/property.h
src/trans-word-level/sequence.cpp

The LHS of the SVA `throughout` operator is a state predicate, not a full property.  Hence, use the appropriate instantiation function.

BMC: LHS of SVA `throughout` is a state predicate

---

regression/ebmc/engine-heuristic/initial1.desc
regression/ebmc/engine-heuristic/initial1.sv
regression/verilog/SVA/initial1.bmc.desc
regression/verilog/SVA/sequence_and1.bmc.desc
regression/verilog/SVA/sequence_and2.bmc.desc
src/ebmc/completeness_threshold.cpp

The completeness threshold engine now considers some CTs that are bigger than one.

BMC: completeness thresholds larger than one

---

regression/smv/expressions/smv_union1.desc

It seems that changes between that PR's original base and current main caused the completeness threshold to shrink.

Fixup regression test after merging #1115

---

src/smvlang/parser.y

This renames the `vardecls` production rule in the SMV parser to `var_list`, to match the NuSMV manual.

SMV: rename `vardecls` to `var_list`

---

src/smvlang/smv_typecheck.cpp

The SMV typechecker now uses the module items for creating the symbols for `VAR` and `DEFINE`.

SMV: use module items for `VAR` and `DEFINE` for creating symbols

---

.github/workflows/pull-request-checks.yaml
regression/ebmc-spot/sva-buechi/sequence_and2.bdd.desc
regression/ebmc-spot/sva-buechi/sequence_or1.bdd.desc
regression/verilog/SVA/sequence_and2.sv
regression/verilog/SVA/sequence_or1.sv

This adds two further tests for the SVA->Buechi->BDD flow.

Two tests for SVA->Buechi->BDD

---

src/smvlang/smv_typecheck.cpp

This avoids the use of the `vars` map in the parse tree.

SMV: submodules are now taken from module items

---

regression/smv/var/already_declared1.desc
regression/smv/var/already_declared1.smv
regression/smv/var/already_declared2.desc
regression/smv/var/already_declared2.smv
regression/smv/var/already_declared3.desc
regression/smv/var/already_declared3.smv
regression/smv/var/already_declared4.desc
regression/smv/var/already_declared4.smv
regression/smv/var/already_declared5.desc
regression/smv/var/already_declared5.smv
src/smvlang/parser.y
src/smvlang/smv_typecheck.cpp

This moves the check whether an identifier for a variable has already been declared from the parser to the type checker.

SMV: move checks for duplicate declarations into type checker

---

CHANGELOG
regression/smv/CTL/smv_ctlspec_AFAG1.bmc.desc
regression/smv/LTL/smv_ltlspec_F4.desc
regression/smv/LTL/smv_ltlspec_F6.desc
regression/smv/LTL/smv_ltlspec_FG1.bmc.desc
regression/smv/LTL/smv_ltlspec_FG1.smv
regression/smv/LTL/smv_ltlspec_FX1.bdd.desc
regression/smv/LTL/smv_ltlspec_FX1.bmc.desc
regression/smv/LTL/smv_ltlspec_FX1.smv
regression/smv/LTL/smv_ltlspec_U3.desc
regression/smv/LTL/smv_ltlspec_U3.smv
regression/smv/LTL/smv_ltlspec_or1.desc
regression/smv/LTL/smv_ltlspec_or2.desc
regression/smv/LTL/smv_ltlspec_or2.smv
regression/verilog/SVA/sva_or1.bmc.desc
regression/verilog/SVA/sva_or1.sv
src/smvlang/smv_typecheck.cpp
src/trans-word-level/property.cpp

This replaces the lasso-shaped encodings in the word-level BMC property encoding.  The lasso and straigth-line encodings are now built as separate obligations.  In the lasso encoding, all operators follow the same lasso shape.  This avoids spurious traces where the eventually operator follows the lasso but a safety part of the property does not.

BMC: reconsider lasso-shaped encodings

---

regression/ebmc-spot/sva-buechi/case1.desc
regression/ebmc-spot/sva-buechi/cover1.desc
regression/ebmc-spot/sva-buechi/cover2.desc
regression/ebmc-spot/sva-buechi/cover_sequence1.bmc.desc
regression/ebmc-spot/sva-buechi/cover_sequence2.bmc.desc
regression/ebmc-spot/sva-buechi/cover_sequence3.bmc.desc
regression/ebmc-spot/sva-buechi/cover_sequence4.bmc.desc
regression/ebmc-spot/sva-buechi/disable_iff1.bmc.desc
regression/ebmc-spot/sva-buechi/empty_sequence1.bmc.desc
regression/ebmc-spot/sva-buechi/followed-by4.bmc.desc
regression/ebmc-spot/sva-buechi/if1.bmc.desc
regression/ebmc-spot/sva-buechi/initial1.bmc.desc
regression/ebmc-spot/sva-buechi/s_always1.desc
regression/ebmc-spot/sva-buechi/sequence1.desc
regression/ebmc-spot/sva-buechi/sequence_and3.desc
regression/ebmc-spot/sva-buechi/sequence_or1.bmc.desc
regression/ebmc-spot/sva-buechi/sequence_repetition1.bdd.desc
regression/ebmc-spot/sva-buechi/sequence_repetition1.bmc.desc
regression/ebmc-spot/sva-buechi/sequence_repetition3.bmc.desc
regression/ebmc-spot/sva-buechi/sva_abort1.bmc.desc
src/ebmc/instrument_buechi.cpp
src/temporal-logic/hoa.h
src/temporal-logic/ltl_to_buechi.cpp
src/temporal-logic/ltl_to_buechi.h

The Buechi automaton accepts counterexamples to the original property.  The Buechi acceptance condition requires a lasso where the loop contains an accepting state.  A proof of that requires satisfying the looping condition, which may require a very long counterexample.
This adds a shortcut using a sufficient condition for a counterexample: we can reject the property when we reach a state in which the Buechi automaton transitions into an accepting state that has an unconditional self-loop on it.  Such traces can always be extended to a lasso as above.

LTL/SVA->Buechi: reject error traces early

---

src/temporal-logic/hoa.cpp
src/temporal-logic/hoa.h
src/temporal-logic/ltl_to_buechi.cpp

The Hanoi Omega-Automata specification requires that numbers of type INT are nonnegative and less than 2^31.  Hence, `uint32_t` suffices, `mp_integer` is not necessary.

Hanoi Omega-Automata INT is 32 bits

---

regression/ebmc-spot/sva-buechi/initial2.desc
regression/ebmc-spot/sva-buechi/static_final1.desc
src/ebmc/instrument_buechi.cpp
src/temporal-logic/ltl_to_buechi.cpp

This adds treatment for the special case where all nonaccepting states of the Buechi automaton have an unconditional self-loop.
In this case, when these nonaccepting states is reached, the trace cannot be extended to an accepting trace, and will hence be rejected.
Hence, in this case, the Buechi acceptance condition is unnecessary, and a simple reachability property is sufficient.

Buechi: identify special cases where reachability is sufficient

---

regression/ebmc-spot/sva-buechi/followed-by5.bdd.desc
regression/ebmc-spot/sva-buechi/followed-by5.bmc.desc
src/temporal-logic/ltl_sva_to_string.cpp

This adds the translation of SVA empty sequences `[*0]` to Spot's input language.

SVA->Buechi: empty sequences

---

regression/ebmc-spot/sva-buechi/cycle_delay_plus4.desc
regression/ebmc-spot/sva-buechi/cycle_delay_star1.bdd.desc
regression/ebmc-spot/sva-buechi/cycle_delay_star1.bmc.desc
regression/ebmc-spot/sva-buechi/cycle_delay_star2.bdd.desc
regression/ebmc-spot/sva-buechi/cycle_delay_star2.bmc.desc
regression/ebmc-spot/sva-buechi/cycle_delay_star3.bdd.desc
regression/ebmc-spot/sva-buechi/cycle_delay_star3.bmc.desc
regression/ebmc-spot/sva-buechi/cycle_delay_star4.desc
regression/verilog/SVA/cycle_delay_star2.desc
regression/verilog/SVA/cycle_delay_star2.sv
src/temporal-logic/ltl_sva_to_string.cpp
src/verilog/sva_expr.h

This fixes the translation of the SVA operators `##[*]` and `##[+]` to Spot's input language.

SVA->Buechi: fix translation of `##[*]` and `##[+]`

---

regression/verilog/property/named_property4.desc
regression/verilog/property/named_property4.sv
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck_expr.h
src/verilog/verilog_typecheck_sva.cpp

Sequences that are in named properties now get the proper weak/strong semantics.
This is achieved by moving the code that assigns the implicit weak/strong semantics from the type checker to the synthesis pass, where named properties are already expanded.

Fix for sequences in named properties

---

CHANGELOG
regression/verilog/initial/initial-zero1.desc
regression/verilog/initial/initial-zero1.sv
src/ebmc/ebmc_parse_options.cpp
src/ebmc/ebmc_parse_options.h
src/ebmc/transition_system.cpp
src/verilog/Makefile
src/verilog/verilog_expr.h
src/verilog/verilog_initializer.cpp
src/verilog/verilog_initializer.h
src/verilog/verilog_language.cpp
src/verilog/verilog_language.h
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis.h
src/verilog/verilog_synthesis_class.h

The SystemVerilog standard specifies that variables are to be zero initialized before simulation begins.  Some synthesis tools generate logic to achieve this, whereas others do not.
This adds the option `--initial-zero` to match the synthesis semantics when appropriate.

SystemVerilog: `--initial-zero`

---

regression/verilog/expressions/index-constant1.desc
regression/verilog/expressions/index-constant1.sv
regression/verilog/expressions/index-constant2.desc
regression/verilog/expressions/index-constant2.sv
src/verilog/verilog_typecheck_expr.cpp

Our `extractbit` IR expression requires a bit-vector argument.  This change converts booleans to bit-vectors when used as vector argument for a Verilog bit select expression.

 Verilog: fix for bit select on boolean argument

---

regression/verilog/property/named_property5.desc
regression/verilog/property/named_property7.desc
regression/verilog/property/named_property7.sv
src/verilog/verilog_typecheck_expr.cpp

SVA named sequences and named properties cannot be used as Booleans.  This adds a check.

Verilog: reject use of SVA sequences and properties as Boolean expression

---

src/ebmc/k_induction.cpp
src/ebmc/k_induction.h

`liveness_to_safety` is already done in `ebmc_parse_options`, hence, there's no need to call it again in `k_induction`.

k-induction: remove redundant call to liveness_to_safety

---

src/verilog/parser.y

This clarifies that the base name of a Verilog scope is always a base name, and never a full identifier.

Verilog parser: scope names are always base names

---

src/verilog/verilog_expr.h
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_typecheck.cpp

Port connections of a module instance can be named or positional.  This adds two helper methods to distinguish these two cases.

Verilog: helper methods for port connections

---

src/verilog/verilog_interfaces.cpp
src/verilog/verilog_synthesis.cpp
src/verilog/verilog_synthesis_class.h
src/verilog/verilog_typecheck.cpp
src/verilog/verilog_typecheck.h
src/verilog/verilog_types.h

This adds the `ports()` member functions to the `module_typet` class, avoiding direct access to the components of the irep.

Verilog: strengthen typing when using module type

---

regression/verilog/asic-world-operators/shift.sv
regression/verilog/expressions/shl4.desc
regression/verilog/expressions/shl4.sv
regression/verilog/expressions/shr4.desc
regression/verilog/expressions/shr4.sv

This moves tests out of asic-world-operators/shift.sv to match the website.

Verilog: Move shift tests

---

src/verilog/verilog_typecheck_expr.cpp

The case of `ID_power` is already handled separately; this removes the dead branch.

Verilog: remove redundant case for `ID_power`

---

regression/verilog/structs/structs4.sv
regression/verilog/structs/unpacked_struct1.desc
regression/verilog/structs/unpacked_struct1.sv
src/verilog/expr2verilog.cpp
src/verilog/parser.y
src/verilog/verilog_elaborate_type.cpp
src/verilog/verilog_typecheck_expr.cpp

This adds enforcement that only packed structs convert to bit-vector types.

Verilog: packed/unpacked structs
